import { useMemo, useState } from 'react';
import { Play, X } from 'lucide-react';
import type { Product } from '../App';
import { readLocalBuilds } from '../lib/localBuilds';

type Props = { products: Product[]; onBack: () => void; onPreview: (product: Product) => void };
type Comparable = { id: string; name: string; type: string; specs: [string, string][]; product?: Product; image?: string; price: number };
const usd = (value: string | number) => `$${(typeof value === 'number' ? value : Number(value.replace(/[^0-9.]/g, '')) || 0).toLocaleString('en-US')}`;
const customPrice = (c: any) => { const pick = (table: Record<string, number>, key: unknown) => table[String(key)] ?? 0; return pick({ standmount: 0, floorstanding: 450, subwoofer: 1400 }, c.brief.format) + pick({ two_way_compact: 2400, two_way_extended: 3200, three_way_reference: 4300, subwoofer_active: 1400 }, c.platformId) + pick({ sealed: 120, ported: 160 }, c.bass.alignment) + pick({ tight: 0, balanced: 80, extended: 160 }, c.bass.bassCharacter) + pick({ compact: 0, standard: 220, large: 520 }, c.cabinet.size) + pick({ none: 0, magnetic_fabric: 90, perforated_metal: 170 }, c.cabinet.grille) + pick({ plinth: 0, slim_feet: 60, stand: 340 }, c.cabinet.base) + pick({ soft_radius: 0, sculpted_radius: 180 }, c.cabinet.edgeProfile) + pick({ walnut: 0, black_ash: 150, satin_white: 120 }, c.cabinet.finish) + pick({ none: 0, engraving: 120, pattern: 220, printed_panel: 350, decal: 160, custom_artwork: 500 }, c.personalisation.kind); };

export default function ComparisonPage({ products, onBack, onPreview }: Props) {
  const localBuilds = readLocalBuilds()?.builds ?? [];
  const catalog: Comparable[] = products.map((product) => ({ id: `catalog:${product.name}`, name: product.name, type: product.type, specs: product.specs, product, image: product.image, price: Number(product.price.replace(/[^0-9.]/g, '')) || 0 }));
  const custom: Comparable[] = localBuilds.map((build) => { const c = build.configuration; const p = build.simulationProfile; const specs: [string, string][] = [['System', p?.referenceName ?? c.platformId.replaceAll('_', ' ')], ['Format', c.brief.format], ['Frequency response', p?.frequencyRangeHz ? `${p.frequencyRangeHz[0]}–${p.frequencyRangeHz[1]} Hz` : 'Pending validation'], ['Sensitivity', p?.sensitivityDb ? `${p.sensitivityDb} dB` : 'Pending validation'], ['Nominal impedance', p?.nominalImpedanceOhm ? `${p.nominalImpedanceOhm} Ω` : 'Pending validation'], ['Maximum SPL', p?.maxSplDb ? `${p.maxSplDb} dB` : 'Pending validation'], ['Crossover frequencies', p?.crossoverHz?.length ? p.crossoverHz.join(' / ') + ' Hz' : 'Platform controlled'], ['Alignment', c.bass.alignment], ['Bass character', c.bass.bassCharacter], ['Net volume', `${c.bass.netVolumeLitres ?? p?.modelInputs?.netVolumeLitres ?? '—'} L`], ['Port tuning', c.bass.tuningHz ? `${c.bass.tuningHz} Hz` : 'Sealed'], ['Cabinet size', c.cabinet.size], ['Cabinet finish', c.cabinet.finish.replaceAll('_', ' ')], ['Grille', c.cabinet.grille.replaceAll('_', ' ')], ['Base', c.cabinet.base.replaceAll('_', ' ')], ['Simulation profile', p?.referenceName ?? 'Not validated']]; return { id: `custom:${build.id}`, name: build.name, type: 'Custom design', image: '/images/components/platform-compact.png', price: customPrice(c), specs }; });
  const choices = [...custom, ...catalog];
  const [selected, setSelected] = useState<Comparable[]>(() => choices.slice(0, Math.min(2, choices.length)));
  const add = (item: Comparable) => setSelected((items) => items.some((candidate) => candidate.id === item.id) ? items.filter((candidate) => candidate.id !== item.id) : items.length >= 5 ? items : [...items, item]);
  const labels = useMemo(() => Array.from(new Set(selected.flatMap((item) => item.specs.map(([label]) => label)))), [selected]);
  return <main className="comparison-page"><button className="back-link" onClick={onBack}>← Back to collection</button><p className="eyebrow">Find your fit</p><h1>Compare the<br /><em>collection.</em></h1><p className="comparison-intro">Select up to five speakers to compare their design, specifications, price, and sound in the same room.</p><div className="compare-picker">{choices.map((item) => <button key={item.id} className={selected.some((candidate) => candidate.id === item.id) ? 'selected' : ''} onClick={() => add(item)} aria-pressed={selected.some((candidate) => candidate.id === item.id)}>{item.name}<small>{selected.some((candidate) => candidate.id === item.id) ? 'Selected' : 'Add'}</small></button>)}</div><p className="compare-count">{selected.length}/5 speakers selected</p>{selected.length > 0 ? <section className="comparison-table"><div className="compare-row compare-head"><span>Speaker</span>{selected.map((item) => <div className="compare-speaker-head" key={item.id}><button className="compare-remove" onClick={() => add(item)} aria-label={`Remove ${item.name}`}><X size={13} /></button>{item.image && <img src={item.image} alt={item.name} />}<strong>{item.name}<small>{item.type}</small><em>{usd(item.price)} <i>per pair</i></em></strong></div>)}</div><div className="compare-row compare-room"><span>Simulation</span>{selected.map((item) => <div key={item.id}><b>Same room</b><small>Listening Lab room type</small>{item.product ? <button onClick={() => onPreview(item.product!)}>Open in Listening Lab →</button> : <small>Validate custom build first</small>}</div>)}</div><div className="compare-row compare-audio"><span>Listen</span>{selected.map((item) => <div className="compare-audio-cell" key={item.id}><label>Original audio<audio controls preload="none" src="/wav/sample-15s.wav" /></label><label>Simulated audio{item.product ? <button className="audio-launch" onClick={() => onPreview(item.product!)}><Play size={12} /> Generate in Listening Lab</button> : <small>Available after validation</small>}</label></div>)}</div>{labels.map((label) => <div className="compare-row" key={label}><span>{label}</span>{selected.map((item) => <strong key={item.id}>{item.specs.find(([spec]) => spec === label)?.[1] ?? '—'}</strong>)}</div>)}</section> : <div className="compare-empty">Choose speakers above to start a comparison.</div>}</main>;
}
