import { useEffect } from 'react';
import type { Product } from '../App';
import AudioPlayer from './AudioPlayer';
import { useAutoSimulation } from '../hooks/useAutoSimulation';
import { useSimulationStore } from '../store/simulation';
import SimulationInsights from './SimulationInsights';

export default function SimulationWorkspace({ products, embedded = false }: { products: Product[]; embedded?: boolean }) {
  const selectedSpeakerId = useSimulationStore((state) => state.selectedSpeakerId); const room = useSimulationStore((state) => state.roomDimensions); const status = useSimulationStore((state) => state.simulationStatus); const result = useSimulationStore((state) => state.simulationResult); const error = useSimulationStore((state) => state.simulationError); const setSelectedSpeaker = useSimulationStore((state) => state.setSelectedSpeaker); const setRoomDimensions = useSimulationStore((state) => state.setRoomDimensions); const retry = useSimulationStore((state) => state.retrySimulation); const customProfile = (() => { try { const saved = window.sessionStorage.getItem('acoustom-custom-speaker-profile'); return saved ? JSON.parse(saved) as { referenceName: string } : null; } catch { return null; } })();
  useAutoSimulation();
  useEffect(() => { if (embedded && customProfile && selectedSpeakerId !== 'custom-reference') setSelectedSpeaker('custom-reference'); }, [embedded, customProfile, selectedSpeakerId, setSelectedSpeaker]);
  return <section className="simulator-grid simulation-workspace"><div className="simulator-controls"><label className="control-label">Speaker</label><div className="simulator-select">{customProfile && <button onClick={() => setSelectedSpeaker('custom-reference')} className={selectedSpeakerId === 'custom-reference' ? 'selected' : ''}><span>Custom reference build</span><small>{customProfile.referenceName}</small></button>}{products.map((product) => <button key={product.name} onClick={() => { window.sessionStorage.removeItem('acoustom-custom-speaker-profile'); setSelectedSpeaker(product.name); }} className={selectedSpeakerId === product.name ? 'selected' : ''}><span>{product.name}</span><small>{product.type}</small></button>)}</div><label className="control-label simulator-label">Room character</label><div className="preset-grid">{(['living_room', 'reflective', 'absorptive'] as const).map((preset) => <button key={preset} onClick={() => setRoomDimensions({ presetId: preset })} className={room.presetId === preset ? 'selected' : ''}><b>{preset.replace('_', ' ')}</b><span>Room response preset</span></button>)}</div><label className="control-label simulator-label">Room dimensions</label><div className="dimension-grid">{(['width', 'length', 'height'] as const).map((key) => <label key={key}>{key}<div><input type="number" min="2" max="20" step=".1" value={room[key]} onChange={(event) => setRoomDimensions({ [key]: event.currentTarget.valueAsNumber })} /><span>m</span></div></label>)}</div><button className="simulate-button" onClick={retry}>Refresh room response <span>→</span></button></div><div className="simulator-listening"><div className={`room-visual ${room.presetId}`}><div className="room-wall" /><div className="speaker-marker left">L</div><div className="listener-marker">LISTEN</div><div className="speaker-marker right">R</div><div className="room-meta">{room.width}m × {room.length}m × {room.height}m</div></div><div className="listen-card"><p className="eyebrow">A/B listening</p><h2>Bring your own track</h2><p>Your audio remains in this browser. Compare the original track with the simulated room response.</p><AudioPlayer /></div></div><div className="workspace-status">{status === 'ready' ? `Response ready · RT60 ${result?.metrics.rt60.toFixed(2)} s` : status === 'simulating' ? 'Calculating room response…' : status === 'error' ? error ?? 'Could not reach the simulator.' : 'Room response updates automatically'}</div>{result && <SimulationInsights result={result} room={room} speakerName={selectedSpeakerId === 'custom-reference' ? customProfile?.referenceName ?? 'Custom reference build' : products.find((product) => product.name === selectedSpeakerId)?.name ?? selectedSpeakerId} />}</section>;
}
