FROM node:22-alpine AS frontend-builder

WORKDIR /app

COPY apps/frontend/package.json apps/frontend/pnpm-lock.yaml ./

RUN corepack enable && pnpm install --frozen-lockfile

COPY apps/frontend/ ./apps/frontend/

RUN cd apps/frontend && pnpm build

FROM nginx:alpine
COPY --from=frontend-builder /app/apps/frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
