import { useEffect, useRef } from 'react';
import type { CustomSpeakerConfiguration } from '@acoustom/types';
import { apiUrl } from '../lib/api';
import { generateBuildSheet } from '../lib/buildSheet';
import { getSharedSimulatedAudio } from '../lib/simulatedAudio';
import { useSimulationStore } from '../store/simulation';

type Product = { name: string; type: string; price: string; tone: string; category: string; description: string; specs: [string, string][] };
export type CartItem = { productName: string; quantity: number };
type Json = Record<string, unknown>;
type Tool = { name: string; title: string; description: string; inputSchema: Json; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute: (input: Json, client?: { signal?: AbortSignal }) => unknown | Promise<unknown> };
type Options = { products: Product[]; getCart: () => CartItem[]; getLiked: () => string[]; getAccessToken: () => string | null | Promise<string | null>; addToCart: (name: string, quantity: number) => CartItem[]; updateCartQuantity: (name: string, quantity: number) => CartItem[]; removeFromCart: (name: string) => CartItem[]; toggleLike: (name: string) => boolean };

const noArgs = { type: 'object', properties: {}, additionalProperties: false };
const productInput = { type: 'object', properties: { productName: { type: 'string', minLength: 1, maxLength: 128, description: 'Exact or case-insensitive Acoustom product name.' } }, required: ['productName'], additionalProperties: false };
const readOnly = { readOnlyHint: true, untrustedContentHint: false };
const action = { readOnlyHint: false, untrustedContentHint: false };
// Saved designs and validated builds include text authored by the signed-in user.
// Marking it lets agent hosts apply their prompt-injection safeguards before use.
const userContentReadOnly = { readOnlyHint: true, untrustedContentHint: true };
const userContentAction = { readOnlyHint: false, untrustedContentHint: true };
const roomProperties = { width: { type: 'number', minimum: 2, maximum: 20, description: 'Metres.' }, length: { type: 'number', minimum: 2, maximum: 20, description: 'Metres.' }, height: { type: 'number', minimum: 2, maximum: 10, description: 'Metres.' }, roomPreset: { type: 'string', enum: ['living_room', 'reflective', 'absorptive'], default: 'living_room' }, surfaceAbsorption: { type: 'object', description: 'Optional absorption coefficients (0 reflective to 1 absorbent) by room surface. Omit to use roomPreset.', properties: { floor: { type: 'number', minimum: 0, maximum: 1 }, ceiling: { type: 'number', minimum: 0, maximum: 1 }, north: { type: 'number', minimum: 0, maximum: 1 }, south: { type: 'number', minimum: 0, maximum: 1 }, east: { type: 'number', minimum: 0, maximum: 1 }, west: { type: 'number', minimum: 0, maximum: 1 } }, additionalProperties: false } };
const speakerPosition = { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' }, z: { type: 'number' }, rotation: { type: 'number', default: 0 }, directivity: { type: 'string', enum: ['omni', 'cardioid'], default: 'omni', description: 'Optional source directivity. Omit for omni.' } }, required: ['x', 'y', 'z'], additionalProperties: false };
const listenerPosition = { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' }, z: { type: 'number' } }, required: ['x', 'y', 'z'], additionalProperties: false };
const roomLayoutProperties = { speakerPositions: { type: 'array', minItems: 2, maxItems: 2, items: speakerPosition, description: 'Optional exact left/right speaker positions in metres. When omitted, Acoustom uses its default stereo layout.' }, listener: { ...listenerPosition, description: 'Optional listening position in metres. Provide with speakerPositions for a custom layout.' } };
const simulationInput = { type: 'object', properties: { ...productInput.properties, ...roomProperties, ...roomLayoutProperties }, required: ['productName', 'width', 'length', 'height'], additionalProperties: false };
const roomEstimateInput: Json = { type: 'object', additionalProperties: false, properties: { width: { type: 'number', minimum: 2, maximum: 20 }, length: { type: 'number', minimum: 2, maximum: 20 }, height: { type: 'number', minimum: 2, maximum: 10 }, presetId: { type: 'string', enum: ['living_room', 'reflective', 'absorptive'] }, speakerPositions: { type: 'array', minItems: 2, maxItems: 2, items: speakerPosition }, listener: listenerPosition, assumptions: { type: 'array', items: { type: 'string', maxLength: 500 } }, confidence: { type: 'object', properties: { dimensions: { type: 'string', enum: ['low', 'medium', 'high'] }, materials: { type: 'string', enum: ['low', 'medium', 'high'] }, layout: { type: 'string', enum: ['low', 'medium', 'high'] } }, additionalProperties: false } }, required: ['width', 'length', 'height', 'presetId', 'speakerPositions', 'listener'], description: 'Best-effort room estimate derived collaboratively from a user-provided image. These values are editable and do not claim physical measurement precision.' };

// Mirrors CustomSpeakerConfiguration at POST /api/custom-speakers/ (camelCase API boundary).
const customBuildInput: Json = {
  type: 'object', additionalProperties: false,
  properties: {
    version: { type: 'integer', const: 1, default: 1 }, name: { type: 'string', minLength: 1, maxLength: 80 },
    brief: { type: 'object', additionalProperties: false, properties: { format: { type: 'string', enum: ['standmount', 'floorstanding', 'subwoofer'] }, soundProfile: { type: 'string', enum: ['balanced', 'reference', 'warm', 'immersive'] }, roomSize: { type: 'string', enum: ['small', 'medium', 'large'] }, listeningDistanceM: { type: 'number', minimum: 1.2, maximum: 6 } }, required: ['format', 'soundProfile', 'roomSize', 'listeningDistanceM'] },
    platformId: { type: 'string', enum: ['two_way_compact', 'two_way_extended', 'three_way_reference', 'subwoofer_active'] },
    bass: { type: 'object', additionalProperties: false, properties: { alignment: { type: 'string', enum: ['sealed', 'ported'] }, bassCharacter: { type: 'string', enum: ['tight', 'balanced', 'extended'] }, tuningHz: { type: 'number', minimum: 24, maximum: 65 }, netVolumeLitres: { type: 'number', exclusiveMinimum: 0, maximum: 250 }, portInnerDiameterMm: { type: 'number', exclusiveMinimum: 0, maximum: 250 }, portLengthMm: { type: 'number', exclusiveMinimum: 0, maximum: 1000 }, dampingDescription: { type: 'string', minLength: 3, maxLength: 500 } }, required: ['alignment', 'bassCharacter'] },
    cabinet: { type: 'object', additionalProperties: false, properties: { size: { type: 'string', enum: ['compact', 'standard', 'large'] }, finish: { type: 'string', enum: ['walnut', 'oak', 'black_ash', 'satin_white', 'satin_black', 'deep_blue', 'custom_colour'] }, finishFamily: { type: 'string', enum: ['veneer', 'paint', 'premium'] }, grille: { type: 'string', enum: ['none', 'magnetic_fabric', 'perforated_metal'] }, base: { type: 'string', enum: ['plinth', 'slim_feet', 'stand'] }, edgeProfile: { type: 'string', enum: ['soft_radius', 'sculpted_radius'], default: 'soft_radius' } }, required: ['size', 'finish', 'finishFamily', 'grille', 'base'] },
    personalisation: { type: 'object', additionalProperties: false, properties: { kind: { type: 'string', enum: ['none', 'engraving', 'pattern', 'printed_panel', 'decal', 'custom_artwork'], default: 'none' }, engraving: { type: 'object', additionalProperties: false, properties: { text: { type: 'string', maxLength: 32 }, font: { type: 'string', enum: ['modern_sans', 'classic_serif'] }, placement: { type: 'string', enum: ['rear_badge', 'side_lower'] } }, required: ['text', 'font', 'placement'] }, artwork: { type: 'object', additionalProperties: false, properties: { assetId: { type: 'string' }, application: { type: 'string', enum: ['side_panel', 'rear_panel', 'grille_badge'] }, treatment: { type: 'string', enum: ['matte_decal', 'uv_print', 'inlaid_pattern'] }, rightsConfirmed: { type: 'boolean' }, status: { type: 'string', enum: ['not_required', 'pending_upload', 'under_review', 'approved', 'rejected'] } }, required: ['application', 'treatment', 'rightsConfirmed'] } }, required: ['kind'] },
  }, required: ['name', 'brief', 'platformId', 'bass', 'cabinet', 'personalisation'],
};

// WebMCP's current standard does not register outputSchema. Keep output
// contracts discoverable here; backend references are generated by FastAPI's
// OpenAPI document, so they cannot drift from the service responses.
const responseSchemas: Record<string, Json> = {
  list_products: { type: 'array', items: { type: 'object', required: ['name', 'type', 'price', 'tone', 'category'] } },
  get_product: { type: 'object', required: ['name', 'type', 'price', 'tone', 'category', 'description', 'specs'] },
  compare_speakers: { type: 'array', items: { type: 'object', required: ['name', 'type', 'price', 'specifications'] } },
  get_room_simulation_presets: { type: 'array', items: { type: 'object', required: ['id', 'name', 'description'] } },
  get_custom_speaker_builder_options: { $ref: '/openapi.json#/components/schemas/CustomSpeakerCatalogResponse' },
  validate_custom_speaker_build: { $ref: '/openapi.json#/components/schemas/CustomSpeakerBuild' },
  generate_custom_build_sheet: { type: 'object', required: ['filename', 'mimeType', 'imageDataUrl', 'build'] },
  get_shared_simulated_audio: { type: 'object', required: ['audioUrl', 'mimeType', 'expiresAt'] },
  get_room_estimate_contract: { type: 'object', required: ['inputSchema', 'guidance'] },
  apply_agent_room_estimate: { type: 'object', required: ['applied', 'room', 'assumptions', 'confidence'] },
  simulate_speaker_in_room: { $ref: '/openapi.json#/components/schemas/SimulationResponse' },
  simulate_custom_speaker_in_room: { $ref: '/openapi.json#/components/schemas/SimulationResponse' },
  get_acoustom_workflow: { type: 'object', required: ['version', 'workflows'] },
  recommend_speakers: { type: 'object', required: ['recommendations'] },
  list_saved_custom_configurations: { type: 'object', required: ['configurations'] },
  get_saved_custom_configuration: { type: 'object', required: ['id', 'configuration', 'revision'] },
  save_custom_configuration: { type: 'object', required: ['id', 'configuration', 'revision'] },
  get_cart: { type: 'object', required: ['items', 'itemCount'] },
  get_wishlist: { type: 'object', required: ['productNames'] },
  add_to_cart: { type: 'object', required: ['ok', 'productName', 'quantity', 'items', 'itemCount'] },
  update_cart_quantity: { type: 'object', required: ['ok', 'productName', 'quantity', 'items', 'itemCount'] },
  remove_from_cart: { type: 'object', required: ['ok', 'removedProductName', 'items', 'itemCount'] },
  toggle_wishlist: { type: 'object', required: ['ok', 'productName', 'currentlyLiked', 'productNames'] },
};

function finite(value: unknown, name: string): number { if (typeof value !== 'number' || !Number.isFinite(value)) throw new Error(`${name} must be a finite number.`); return value; }
async function apiJson(response: Response, operation: string): Promise<unknown> { if (response.ok) return response.json(); const body = await response.json().catch(() => null) as { detail?: unknown } | null; const detail = typeof body?.detail === 'string' ? body.detail : body?.detail ? JSON.stringify(body.detail) : `HTTP ${response.status}`; throw new Error(`${operation} failed: ${detail}`); }

/** Imperative WebMCP registration; the app remains usable when the API is unavailable. */
export function useWebMcp(options: Options): void {
  const latest = useRef(options);
  useEffect(() => { latest.current = options; }, [options]);
  useEffect(() => {
    const context = document.modelContext;
    if (!context?.registerTool) return;
    const controller = new AbortController();
    const find = (name: unknown) => typeof name === 'string' ? latest.current.products.find((item) => item.name.toLowerCase() === name.toLowerCase()) : undefined;
    const authenticatedHeaders = async () => { const token = await latest.current.getAccessToken(); if (!token) throw new Error('The user must sign in before working with saved configurations.'); return { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }; };
    const stereoLayout = (width: number, length: number, height: number) => ({ speakers: [{ x: width * .24, y: Math.min(.7, length * .2), z: Math.min(1, height - .1), rotation: 15 }, { x: width * .76, y: Math.min(.7, length * .2), z: Math.min(1, height - .1), rotation: -15 }], listener: { x: width * .5, y: length * .78, z: Math.min(1.1, height - .1) } });
    const layout = (width: number, length: number, height: number, speakerPositions: unknown, listener: unknown) => speakerPositions === undefined && listener === undefined ? stereoLayout(width, length, height) : { speakers: speakerPositions, listener };
    const tools: Tool[] = [
      { name: 'get_webmcp_tool_contract', title: 'Get a WebMCP tool contract', description: 'Returns the input schema and response schema for a registered Acoustom WebMCP tool. Backend response schemas reference the live FastAPI OpenAPI document.', inputSchema: { type: 'object', properties: { toolName: { type: 'string', enum: Object.keys(responseSchemas) } }, required: ['toolName'], additionalProperties: false }, annotations: readOnly, execute: ({ toolName }) => { if (typeof toolName !== 'string' || !responseSchemas[toolName]) throw new Error(`Unknown WebMCP tool: ${String(toolName)}`); const tool = tools.find((candidate) => candidate.name === toolName); if (!tool) throw new Error(`Registered tool unavailable: ${toolName}`); return { name: tool.name, inputSchema: tool.inputSchema, responseSchema: responseSchemas[toolName] }; } },
      { name: 'get_acoustom_workflow', title: 'Get Acoustom workflow guide', description: 'Returns the recommended agent workflows, tool order, purpose, and the output fields to carry to each next step.', inputSchema: noArgs, annotations: readOnly, execute: () => ({ version: 1, workflows: [
        { id: 'catalogue_research', purpose: 'Recommend, inspect, compare and test catalog speakers for stated room and listening requirements.', steps: [{ tool: 'recommend_speakers', optional: true, useOutput: 'Use ranked product names and stated matching reasons.' }, { tool: 'list_products', useOutput: 'Choose product names.' }, { tool: 'get_product', useOutput: 'Use complete details and specifications.' }, { tool: 'compare_speakers', optional: true, useOutput: 'Compare two or three selected products.' }, { tool: 'simulate_speaker_in_room', optional: true, useOutput: 'Return in-room frequency response, impulse-response URLs, RT60, and profile provenance.' }] },
        { id: 'custom_build_simulation', purpose: 'Validate a curated custom speaker, generate an accurate catalog sheet, and simulate its returned engineering profile.', steps: [{ tool: 'get_custom_speaker_builder_options', useOutput: 'Choose a server-owned platform.' }, { tool: 'validate_custom_speaker_build', useOutput: 'Pass the entire returned build as build to simulate_custom_speaker_in_room.' }, { tool: 'generate_custom_build_sheet', optional: true, useOutput: 'Returns a PNG data URL for the validated build sheet.' }, { tool: 'simulate_custom_speaker_in_room', useOutput: 'Return impulse-response URLs and RT60.' }] },
        { id: 'shared_simulation_audio', purpose: 'Return a playable, browser-rendered room-simulation WAV after the user has explicitly approved sharing their source track.', steps: [{ tool: 'simulate_speaker_in_room | simulate_custom_speaker_in_room', useOutput: 'The browser uses the returned impulse responses to render its audio.' }, { tool: 'get_shared_simulated_audio', useOutput: 'Returns the temporary playable WAV URL, MIME type, and expiry after the user clicks Share with agent.' }], constraints: ['Never claim that an impulse-response URL is a rendered music track.', 'If get_shared_simulated_audio reports no asset, ask the user to select a track and click Share with agent in the listening lab.', 'The audio URL is temporary and represents user-authorized content.'] },
        { id: 'room_image_collaboration', purpose: 'Translate a user-provided room image into an editable, best-effort simulation proposal without implying precise measurement.', steps: [{ tool: 'get_room_estimate_contract', useOutput: 'Follow the exact accepted fields and collaborative guidance.' }, { tool: 'apply_agent_room_estimate', useOutput: 'Populates the browser room controls; the user may refine the estimate and simulate immediately.' }], constraints: ['Inspect the image only when it is available to the agent through the conversation or a user-approved asset.', 'State assumptions and confidence; image-derived dimensions are estimates, not measurements.', 'Ask for a known reference measurement when it would materially improve the estimate.'] },
        { id: 'refine_saved_build', purpose: 'Load an existing build, alter it in response to user feedback, revalidate its engineering profile, simulate it, and save the next revision.', steps: [{ tool: 'list_saved_custom_configurations | get_saved_custom_configuration', useOutput: 'Use configuration and revision from the saved design.' }, { tool: 'validate_custom_speaker_build', useOutput: 'Submit the revised configuration before simulation.' }, { tool: 'simulate_custom_speaker_in_room', useOutput: 'Use the validation result as build.' }, { tool: 'save_custom_configuration', useOutput: 'Pass configurationId, current expectedRevision, and the revised configuration.' }] },
        { id: 'shopping_bag', purpose: 'Inspect or change the browser-local bag and wishlist. These changes are not a checkout or purchase.', steps: [{ tool: 'get_cart', useOutput: 'Inspect current bag.' }, { tool: 'add_to_cart | update_cart_quantity | remove_from_cart', useOutput: 'Use returned items and itemCount as the new state.' }, { tool: 'get_wishlist | toggle_wishlist', useOutput: 'Use returned productNames as the new state.' }] },
      ] }) },
      { name: 'recommend_speakers', title: 'Recommend speakers', description: 'Ranks catalog speakers for room size, listening preference, preferred format, and budget. Returns transparent matching reasons; use get_product and simulation to inspect recommendations.', inputSchema: { type: 'object', properties: { roomSize: { type: 'string', enum: ['small', 'medium', 'large'] }, soundProfile: { type: 'string', enum: ['balanced', 'reference', 'warm', 'immersive'] }, preferredFormat: { type: 'string', enum: ['standmount', 'floorstanding', 'active'] }, budgetEur: { type: 'number', minimum: 0 }, feedback: { type: 'string', maxLength: 2_000, description: 'Optional user feedback that the chatbot should consider when explaining or refining the recommendation.' } }, additionalProperties: false }, annotations: userContentReadOnly, execute: ({ roomSize, soundProfile, preferredFormat, budgetEur, feedback }) => { const guidance: Record<string, { rooms: string[]; profiles: string[]; format: string }> = { 'Contour 20i': { rooms: ['small', 'medium'], profiles: ['balanced', 'reference'], format: 'standmount' }, 'Confidence 20': { rooms: ['small', 'medium'], profiles: ['reference'], format: 'standmount' }, 'Emit 50': { rooms: ['medium', 'large'], profiles: ['balanced', 'immersive'], format: 'floorstanding' }, 'Aether 7': { rooms: ['large'], profiles: ['reference', 'immersive'], format: 'floorstanding' }, 'Terra One': { rooms: ['small', 'medium'], profiles: ['warm', 'balanced'], format: 'active' }, 'Vector 12': { rooms: ['small', 'medium'], profiles: ['reference'], format: 'active' } }; const budget = typeof budgetEur === 'number' ? budgetEur : undefined; return { feedback: typeof feedback === 'string' ? feedback : undefined, recommendations: latest.current.products.map((product) => { const guide = guidance[product.name]; const price = Number(product.price.replace(/[^0-9.]/g, '')); const reasons = []; let score = 0; if (guide?.rooms.includes(String(roomSize))) { score += 2; reasons.push(`suited to a ${roomSize} room`); } if (guide?.profiles.includes(String(soundProfile))) { score += 2; reasons.push(`matches the ${soundProfile} listening preference`); } if (guide?.format === preferredFormat) { score += 1; reasons.push(`matches the preferred ${preferredFormat} format`); } if (budget === undefined || price <= budget) { score += 1; reasons.push(budget === undefined ? 'no budget limit was supplied' : `within the €${budget} budget`); } return { productName: product.name, score, reasons, priceEur: price }; }).sort((a, b) => b.score - a.score || a.priceEur - b.priceEur) }; } },
      { name: 'list_products', title: 'List speakers', description: 'Returns the current Acoustom catalog: name, type, price, tone, and category.', inputSchema: noArgs, annotations: readOnly, execute: () => latest.current.products.map(({ name, type, price, tone, category }) => ({ name, type, price, tone, category })) },
      { name: 'get_product', title: 'Get speaker details', description: 'Returns complete current-page details and specifications for one catalog speaker.', inputSchema: productInput, annotations: readOnly, execute: ({ productName }) => { const product = find(productName); if (!product) throw new Error(`Product not found: ${String(productName)}`); return product; } },
      { name: 'compare_speakers', title: 'Compare speakers', description: 'Returns specifications for two or three catalog speakers.', inputSchema: { type: 'object', properties: { productNames: { type: 'array', minItems: 2, maxItems: 3, items: { type: 'string', minLength: 1, maxLength: 128 } } }, required: ['productNames'], additionalProperties: false }, annotations: readOnly, execute: ({ productNames }) => { if (!Array.isArray(productNames) || productNames.length < 2 || productNames.length > 3) throw new Error('Choose two or three speaker names.'); const products = productNames.map(find); if (products.some((item) => !item)) throw new Error('One or more speakers were not found.'); return (products as Product[]).map(({ name, type, price, specs }) => ({ name, type, price, specifications: Object.fromEntries(specs) })); } },
      { name: 'get_room_simulation_presets', title: 'List room presets', description: 'Returns the room-acoustic presets accepted by simulate_speaker_in_room.', inputSchema: noArgs, annotations: readOnly, execute: () => [{ id: 'living_room', name: 'Living room', description: 'Balanced furnishings and everyday surfaces.' }, { id: 'reflective', name: 'Loft / studio', description: 'Harder surfaces and longer, brighter decay.' }, { id: 'absorptive', name: 'Treated room', description: 'Soft furnishings and acoustic treatment.' }] },
      { name: 'get_room_estimate_contract', title: 'Get room-image estimate contract', description: 'Returns the schema and collaboration guidance for translating a user-provided room image into editable simulation inputs. This tool does not analyse images itself.', inputSchema: noArgs, annotations: readOnly, execute: () => ({ inputSchema: roomEstimateInput, guidance: ['Use a user-provided room image only when it is visible to you.', 'Treat all image-derived dimensions as estimates and include assumptions/confidence.', 'A known reference measurement improves scale but is optional.', 'The user can revise the applied fields at any time.'] }) },
      { name: 'apply_agent_room_estimate', title: 'Apply agent room estimate', description: 'Applies an agent’s best-effort image-based room estimate to the live browser simulation controls. This is collaborative, editable, and intentionally not a hard confirmation gate.', inputSchema: roomEstimateInput, annotations: userContentAction, execute: ({ width, length, height, presetId, speakerPositions, listener, assumptions = [], confidence = {} }) => { const store = useSimulationStore.getState(); store.setRoomDimensions({ width: finite(width, 'width'), length: finite(length, 'length'), height: finite(height, 'height'), presetId: String(presetId) }); const positions = speakerPositions as Array<Record<string, unknown>>; const target = listener as Record<string, unknown>; store.setSpeakerPosition('left', { x: finite(positions[0].x, 'speakerPositions[0].x'), y: finite(positions[0].y, 'speakerPositions[0].y'), z: finite(positions[0].z, 'speakerPositions[0].z'), rotation: typeof positions[0].rotation === 'number' ? positions[0].rotation : 0 }); store.setSpeakerPosition('right', { x: finite(positions[1].x, 'speakerPositions[1].x'), y: finite(positions[1].y, 'speakerPositions[1].y'), z: finite(positions[1].z, 'speakerPositions[1].z'), rotation: typeof positions[1].rotation === 'number' ? positions[1].rotation : 0 }); store.setListenerPosition({ x: finite(target.x, 'listener.x'), y: finite(target.y, 'listener.y'), z: finite(target.z, 'listener.z') }); return { applied: true, room: { width, length, height, presetId }, assumptions, confidence }; } },
      { name: 'get_shared_simulated_audio', title: 'Get shared simulated audio', description: 'Returns the playable URL for the latest browser-rendered WAV that the user explicitly shared with the agent. The URL expires automatically.', inputSchema: noArgs, annotations: readOnly, execute: () => { const asset = getSharedSimulatedAudio(); if (!asset) throw new Error('No simulated audio has been shared. Ask the user to choose Share with agent in the listening lab.'); return asset; } },
      { name: 'get_custom_speaker_builder_options', title: 'Get custom builder options', description: 'Returns server-owned custom-speaker platforms. All other accepted builder values are enumerated by validate_custom_speaker_build.', inputSchema: noArgs, annotations: readOnly, execute: async (_input, client) => apiJson(await fetch(apiUrl('/api/custom-speakers/catalog'), { signal: client?.signal }), 'Loading builder options') },
      { name: 'validate_custom_speaker_build', title: 'Validate custom speaker build', description: 'Validates and derives a curated build. This does not purchase anything; it returns the validated build, simulation profile, warnings, and measurement requirements.', inputSchema: customBuildInput, annotations: userContentAction, execute: async (input, client) => apiJson(await fetch(apiUrl('/api/custom-speakers/'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version: 1, ...input } as CustomSpeakerConfiguration), signal: client?.signal }), 'Custom-speaker validation') },
      { name: 'generate_custom_build_sheet', title: 'Generate custom build sheet', description: 'Validates a custom configuration and renders a downloadable two-angle catalog build-sheet PNG. Returns the validated build plus imageDataUrl, which an agent can present as an image attachment. The custom builder must be open in this browser so its 3D renderer is available.', inputSchema: customBuildInput, annotations: userContentAction, execute: async (input, client) => { const build = await apiJson(await fetch(apiUrl('/api/custom-speakers/'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version: 1, ...input } as CustomSpeakerConfiguration), signal: client?.signal }), 'Custom-speaker validation') as CustomSpeakerConfiguration & { derived: import('@acoustom/types').DerivedSpeakerSpecifications }; const imageDataUrl = await generateBuildSheet({ configuration: build, derived: build.derived }); const filename = `acoustom-${build.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'custom-build'}-build-sheet.png`; return { filename, mimeType: 'image/png', imageDataUrl, build }; } },
      { name: 'list_saved_custom_configurations', title: 'List saved custom designs', description: 'Lists the signed-in user’s durable custom speaker designs. Use an id from this result to load or edit a shared configuration.', inputSchema: noArgs, annotations: userContentReadOnly, execute: async (_input, client) => apiJson(await fetch(apiUrl('/api/configurations/'), { headers: await authenticatedHeaders(), signal: client?.signal }), 'Loading saved configurations') },
      { name: 'get_saved_custom_configuration', title: 'Get saved custom design', description: 'Loads one saved custom-speaker configuration and its current revision for collaborative editing.', inputSchema: { type: 'object', properties: { configurationId: { type: 'string', minLength: 1, maxLength: 128 } }, required: ['configurationId'], additionalProperties: false }, annotations: userContentReadOnly, execute: async ({ configurationId }, client) => apiJson(await fetch(apiUrl(`/api/configurations/${encodeURIComponent(String(configurationId))}`), { headers: await authenticatedHeaders(), signal: client?.signal }), 'Loading configuration') },
      { name: 'save_custom_configuration', title: 'Save custom design', description: 'Creates or updates a saved custom-speaker design for the signed-in user. For an update, pass the id and current revision returned by get_saved_custom_configuration; changes are recorded as an agent revision.', inputSchema: { type: 'object', properties: { configurationId: { type: 'string', maxLength: 128 }, expectedRevision: { type: 'integer', minimum: 1 }, configuration: customBuildInput }, required: ['configuration'], additionalProperties: false }, annotations: userContentAction, execute: async ({ configurationId, expectedRevision, configuration }, client) => { const updating = typeof configurationId === 'string' && configurationId.length > 0; return apiJson(await fetch(apiUrl(updating ? `/api/configurations/${encodeURIComponent(configurationId)}` : '/api/configurations/'), { method: updating ? 'PUT' : 'POST', headers: await authenticatedHeaders(), body: JSON.stringify({ configuration: { version: 1, ...(configuration as Json) }, expectedRevision, actor: 'agent' }), signal: client?.signal }), 'Saving configuration'); } },
      { name: 'simulate_speaker_in_room', title: 'Simulate speaker in room', description: 'Runs a speaker-specific stereo room simulation for one catalog speaker. Returns its profile provenance, in-room frequency response, impulse-response URLs, and RT60. Detailed room surfaces and cardioid sources are optional.', inputSchema: simulationInput, annotations: action, execute: async ({ productName, width: rawWidth, length: rawLength, height: rawHeight, roomPreset = 'living_room', surfaceAbsorption, speakerPositions, listener }, client) => { const product = find(productName); if (!product) throw new Error(`Product not found: ${String(productName)}`); const width = finite(rawWidth, 'width'), length = finite(rawLength, 'length'), height = finite(rawHeight, 'height'); return apiJson(await fetch(apiUrl('/api/simulate'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ speakerId: product.name, room: { width, length, height, presetId: roomPreset, ...(surfaceAbsorption ? { surfaceAbsorption } : {}) }, ...layout(width, length, height, speakerPositions, listener) }), signal: client?.signal }), 'Room simulation'); } },
      { name: 'simulate_custom_speaker_in_room', title: 'Simulate validated custom build', description: 'Runs room simulation for the entire build returned by validate_custom_speaker_build. Pass that returned object unchanged as build; detailed room surfaces and source placement are optional.', inputSchema: { type: 'object', properties: { build: { type: 'object', required: ['derived'], properties: { derived: { type: 'object', required: ['simulationProfile'] } } }, ...roomProperties, ...roomLayoutProperties }, required: ['build', 'width', 'length', 'height'], additionalProperties: false }, annotations: action, execute: async ({ build, width: rawWidth, length: rawLength, height: rawHeight, roomPreset = 'living_room', surfaceAbsorption, speakerPositions, listener }, client) => { if (!build || typeof build !== 'object') throw new Error('build must be the object returned by validate_custom_speaker_build.'); const profile = (build as Json).derived; if (!profile || typeof profile !== 'object' || !(profile as Json).simulationProfile || typeof (profile as Json).simulationProfile !== 'object') throw new Error('build.derived.simulationProfile is required.'); const simulationProfile = (profile as Json).simulationProfile as Json; const status = simulationProfile.status, referenceId = simulationProfile.referenceId; if ((status !== 'reference_ready' && status !== 'component_model_ready') || typeof referenceId !== 'string') throw new Error('The build does not contain a simulatable speaker profile.'); const width = finite(rawWidth, 'width'), length = finite(rawLength, 'length'), height = finite(rawHeight, 'height'); const speakerProfile = { status, referenceId, ...(simulationProfile.modelInputs ? { modelInputs: simulationProfile.modelInputs } : {}) }; return apiJson(await fetch(apiUrl('/api/simulate'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ speakerId: 'custom-reference', speakerProfile, room: { width, length, height, presetId: roomPreset, ...(surfaceAbsorption ? { surfaceAbsorption } : {}) }, ...layout(width, length, height, speakerPositions, listener) }), signal: client?.signal }), 'Custom-build room simulation'); } },
      { name: 'get_cart', title: 'View shopping bag', description: 'Returns current shopping-bag items and total item count.', inputSchema: noArgs, annotations: readOnly, execute: () => { const items = latest.current.getCart(); return { items, itemCount: items.reduce((total, item) => total + item.quantity, 0) }; } },
      { name: 'get_wishlist', title: 'View wishlist', description: 'Returns names of catalog speakers currently saved in the wishlist.', inputSchema: noArgs, annotations: readOnly, execute: () => ({ productNames: latest.current.getLiked() }) },
      { name: 'add_to_cart', title: 'Add to bag', description: 'Adds one to ten pairs of a catalog speaker to the current shopping bag.', inputSchema: { type: 'object', properties: { ...productInput.properties, quantity: { type: 'integer', minimum: 1, maximum: 10, default: 1 } }, required: ['productName'], additionalProperties: false }, annotations: action, execute: ({ productName, quantity = 1 }) => { const product = find(productName); if (!product) throw new Error(`Product not found: ${String(productName)}`); if (!Number.isInteger(quantity) || (quantity as number) < 1 || (quantity as number) > 10) throw new Error('quantity must be an integer from 1 to 10.'); const items = latest.current.addToCart(product.name, quantity as number); return { ok: true, productName: product.name, quantity, items, itemCount: items.reduce((total, item) => total + item.quantity, 0) }; } },
      { name: 'update_cart_quantity', title: 'Update bag quantity', description: 'Sets a speaker quantity in the current bag; use zero to remove it.', inputSchema: { type: 'object', properties: { ...productInput.properties, quantity: { type: 'integer', minimum: 0, maximum: 10 } }, required: ['productName', 'quantity'], additionalProperties: false }, annotations: action, execute: ({ productName, quantity }) => { const product = find(productName); if (!product) throw new Error(`Product not found: ${String(productName)}`); if (!Number.isInteger(quantity) || (quantity as number) < 0 || (quantity as number) > 10) throw new Error('quantity must be an integer from 0 to 10.'); const items = latest.current.updateCartQuantity(product.name, quantity as number); return { ok: true, productName: product.name, quantity, items, itemCount: items.reduce((total, item) => total + item.quantity, 0) }; } },
      { name: 'remove_from_cart', title: 'Remove from bag', description: 'Removes a catalog speaker completely from the current shopping bag.', inputSchema: productInput, annotations: action, execute: ({ productName }) => { const product = find(productName); if (!product) throw new Error(`Product not found: ${String(productName)}`); const items = latest.current.removeFromCart(product.name); return { ok: true, removedProductName: product.name, items, itemCount: items.reduce((total, item) => total + item.quantity, 0) }; } },
      { name: 'toggle_wishlist', title: 'Toggle wishlist', description: 'Saves a catalog speaker to the wishlist, or removes it if already saved.', inputSchema: productInput, annotations: action, execute: ({ productName }) => { const product = find(productName); if (!product) throw new Error(`Product not found: ${String(productName)}`); const currentlyLiked = latest.current.toggleLike(product.name); return { ok: true, productName: product.name, currentlyLiked, productNames: latest.current.getLiked() }; } },
    ];
    void Promise.all(tools.map((tool) => context.registerTool(tool, { signal: controller.signal }))).catch((error: unknown) => { if (!controller.signal.aborted) console.warn('[WebMCP] registration failed', error); });
    return () => controller.abort();
  }, []);
}
