"""Single authoritative catalog used by the storefront, comparison page, and WebMCP tools.

Every speaker shares the same set of spec keys so the comparison matrix never
shows missing data.  Simulation profiles in ``catalog_profiles`` derive their
numeric values from this catalog to keep the two in sync.
"""

SPEC_KEYS = [
    "System",
    "Frequency response",
    "Sensitivity",
    "Nominal impedance",
    "Recommended amplifier power",
    "Crossover frequency",
    "Maximum SPL",
    "Amplification",
    "Cabinet materials",
    "Cabinet finishes",
    "Grille",
    "Base",
    "Directivity",
    "Inputs",
    "Calibration",
    "Dimensions (H × W × D)",
    "Weight",
]

PUBLIC_CATALOG = [
    {
        "name": "Contour 20i",
        "type": "Standmount speaker",
        "price": "€5,000",
        "image": "/images/contour-20i.png",
        "tone": "New",
        "category": "Contour series",
        "description": "A meticulously balanced loudspeaker for people who want to get closer to the music. Open, honest, and effortless from the very first listen.",
        "specs": [
            ["System", "2-way rear-ported standmount"],
            ["Frequency response", "42 Hz – 25 kHz (±3 dB)"],
            ["Sensitivity", "86 dB (2.83 V / 1 m)"],
            ["Nominal impedance", "4 Ω (3.1 Ω minimum)"],
            ["Recommended amplifier power", "60 – 200 W"],
            ["Crossover frequency", "2.1 kHz"],
            ["Maximum SPL", "108 dB at 1 m"],
            ["Amplification", "Passive (external amplification required)"],
            ["Cabinet materials", "MDF with internal bracing"],
            ["Cabinet finishes", "Natural walnut / Black ash"],
            ["Grille", "Magnetic black fabric"],
            ["Base", "Integrated plinth with decoupling feet"],
            ["Directivity", "—"],
            ["Inputs", "Single-wired speaker terminals"],
            ["Calibration", "—"],
            ["Dimensions (H × W × D)", "440 × 215 × 360 mm"],
            ["Weight", "15 kg each"],
        ],
    },
    {
        "name": "Confidence 20",
        "type": "High-end standmount",
        "price": "€32,000",
        "image": "/images/confidence-20.png",
        "tone": "Signature",
        "category": "Confidence series",
        "description": "A reference standmount speaker with a wide, precise soundstage and the composure to reveal every nuance in your favourite recording.",
        "specs": [
            ["System", "2-way Esotar reference standmount"],
            ["Frequency response", "39 Hz – 28 kHz (±3 dB)"],
            ["Sensitivity", "87 dB (2.83 V / 1 m)"],
            ["Nominal impedance", "6 Ω (4.0 Ω minimum)"],
            ["Recommended amplifier power", "100 – 300 W"],
            ["Crossover frequency", "2.35 kHz"],
            ["Maximum SPL", "110 dB at 1 m"],
            ["Amplification", "Passive (external amplification required)"],
            ["Cabinet materials", "Composite sandwich with aluminium baffle"],
            ["Cabinet finishes", "Black high gloss / Walnut veneer"],
            ["Grille", "Magnetic black leather"],
            ["Base", "Polished aluminium plinth"],
            ["Directivity", "—"],
            ["Inputs", "Bi-wired speaker terminals"],
            ["Calibration", "—"],
            ["Dimensions (H × W × D)", "520 × 250 × 430 mm"],
            ["Weight", "27 kg each"],
        ],
    },
    {
        "name": "Emit 50",
        "type": "Floorstanding speaker",
        "price": "€2,200",
        "image": "/images/emit-50.png",
        "tone": "Best seller",
        "category": "Emit series",
        "description": "Room-filling, energetic sound in a beautifully proportioned floorstander designed to make every playlist more engaging.",
        "specs": [
            ["System", "3-way twin-woofer floorstander"],
            ["Frequency response", "31 Hz – 25 kHz (±3 dB)"],
            ["Sensitivity", "88.5 dB (2.83 V / 1 m)"],
            ["Nominal impedance", "6 Ω"],
            ["Recommended amplifier power", "40 – 180 W"],
            ["Crossover frequency", "430 Hz / 3.1 kHz"],
            ["Maximum SPL", "109 dB at 1 m"],
            ["Amplification", "Passive (external amplification required)"],
            ["Cabinet materials", "MDF with internal bracing"],
            ["Cabinet finishes", "Black ash / White satin"],
            ["Grille", "Removable grey fabric"],
            ["Base", "Outrigger plinth with spikes"],
            ["Directivity", "—"],
            ["Inputs", "Bi-wired speaker terminals"],
            ["Calibration", "—"],
            ["Dimensions (H × W × D)", "900 × 290 × 310 mm"],
            ["Weight", "22 kg each"],
        ],
    },
    {
        "name": "Aether 7",
        "type": "Transparent floorstanding speaker",
        "price": "€18,900",
        "image": "/images/aether-glass-floorstander.png",
        "tone": "Material study",
        "category": "Aether series",
        "description": "A sculptural four-way system housed in acoustically inert smoked glass. The cabinet disappears visually while its exposed driver architecture makes every detail feel intentional.",
        "specs": [
            ["System", "4-way open-frame glass floorstander"],
            ["Frequency response", "24 Hz – 32 kHz (±3 dB)"],
            ["Sensitivity", "91 dB (2.83 V / 1 m)"],
            ["Nominal impedance", "8 Ω (5.2 Ω minimum)"],
            ["Recommended amplifier power", "100 – 500 W"],
            ["Crossover frequency", "180 Hz / 1.8 kHz / 7.5 kHz"],
            ["Maximum SPL", "116 dB at 1 m"],
            ["Amplification", "Passive (external amplification required)"],
            ["Cabinet materials", "Smoked acoustic glass / Brushed aluminium"],
            ["Cabinet finishes", "Smoked glass / Brushed aluminium"],
            ["Grille", "Open-frame (no grille)"],
            ["Base", "Machined aluminium outrigger"],
            ["Directivity", "—"],
            ["Inputs", "Single-wired speaker terminals"],
            ["Calibration", "—"],
            ["Dimensions (H × W × D)", "1180 × 290 × 390 mm"],
            ["Weight", "41 kg each"],
        ],
    },
    {
        "name": "Terra One",
        "type": "Wireless sculptural speaker",
        "price": "€2,800",
        "image": "/images/terra-composite-wireless.png",
        "tone": "New material",
        "category": "Terra series",
        "description": "A compact active speaker cast from recycled mineral composite. Soft in silhouette, remarkably dense in sound, and designed to sit naturally in contemporary spaces.",
        "specs": [
            ["System", "Coaxial active speaker with rear radiator"],
            ["Frequency response", "36 Hz – 21 kHz (±3 dB)"],
            ["Sensitivity", "88 dB (built-in amplification)"],
            ["Nominal impedance", "Active input"],
            ["Recommended amplifier power", "Built-in 280 W class-D"],
            ["Crossover frequency", "Active DSP crossover"],
            ["Maximum SPL", "104 dB at 1 m"],
            ["Amplification", "280 W class-D with DSP"],
            ["Cabinet materials", "Recycled mineral composite / Graphite textile"],
            ["Cabinet finishes", "Graphite textile / Bone white"],
            ["Grille", "Integral fabric wrap"],
            ["Base", "Cast composite with silicone decouplers"],
            ["Directivity", "Coaxial constant directivity"],
            ["Inputs", "Wireless / Balanced XLR / RCA"],
            ["Calibration", "Built-in room correction (8-band EQ)"],
            ["Dimensions (H × W × D)", "410 × 290 × 260 mm"],
            ["Weight", "12.5 kg each"],
        ],
    },
    {
        "name": "Vector 12",
        "type": "Aluminium active monitor",
        "price": "€6,400",
        "image": "/images/vector-12.png",
        "tone": "Studio edition",
        "category": "Vector series",
        "description": "A precision active monitor machined from recycled aluminium. Its wave-guided tweeter and DSP alignment deliver controlled, close-field clarity without a conventional cabinet.",
        "specs": [
            ["System", "3-way DSP active nearfield monitor"],
            ["Frequency response", "28 Hz – 26 kHz (±2 dB)"],
            ["Sensitivity", "90 dB (built-in amplification)"],
            ["Nominal impedance", "Balanced line input"],
            ["Recommended amplifier power", "Built-in 500 W tri-amp"],
            ["Crossover frequency", "Active DSP crossover"],
            ["Maximum SPL", "112 dB at 1 m"],
            ["Amplification", "500 W tri-amplified (ICEpower)"],
            ["Cabinet materials", "Recycled aluminium / Space-black anodise"],
            ["Cabinet finishes", "Space-black anodised aluminium"],
            ["Grille", "Removable perforated aluminium"],
            ["Base", "Integrated stand-mount thread"],
            ["Directivity", "90° × 50° waveguide"],
            ["Inputs", "Balanced XLR / AES3 / USB-C"],
            ["Calibration", "Network room EQ with 8 filters"],
            ["Dimensions (H × W × D)", "470 × 260 × 330 mm"],
            ["Weight", "18 kg each"],
        ],
    },
]