"""Single authoritative catalog used by the storefront and WebMCP tools."""

PUBLIC_CATALOG = [
    {"name": "Contour 20i", "type": "Standmount speaker", "price": "€5,000", "image": "/images/contour-20i.png", "tone": "New", "category": "Contour series", "description": "A meticulously balanced loudspeaker for people who want to get closer to the music. Open, honest, and effortless from the very first listen.", "specs": [["System", "2-way rear-ported standmount"], ["Frequency response", "42 Hz – 25 kHz (±3 dB)"], ["Sensitivity", "86 dB (2.83 V / 1 m)"], ["Nominal impedance", "4 Ω (3.1 Ω minimum)"], ["Recommended amplifier power", "60 – 200 W"], ["Crossover frequency", "2.1 kHz"], ["Dimensions (H × W × D)", "440 × 215 × 360 mm"], ["Weight", "15 kg each"], ["Cabinet finishes", "Natural walnut / Black ash"]]},
    {"name": "Confidence 20", "type": "High-end standmount", "price": "€32,000", "image": "/images/confidence-20.png", "tone": "Signature", "category": "Confidence series", "description": "A reference standmount speaker with a wide, precise soundstage and the composure to reveal every nuance in your favourite recording.", "specs": [["System", "2-way Esotar reference standmount"], ["Frequency response", "39 Hz – 28 kHz (±3 dB)"], ["Sensitivity", "87 dB (2.83 V / 1 m)"], ["Nominal impedance", "6 Ω (4.0 Ω minimum)"], ["Recommended amplifier power", "100 – 300 W"], ["Crossover frequency", "2.35 kHz"], ["Dimensions (H × W × D)", "520 × 250 × 430 mm"], ["Weight", "27 kg each"], ["Cabinet finishes", "Black high gloss / Walnut veneer"]]},
    {"name": "Emit 50", "type": "Floorstanding speaker", "price": "€2,200", "image": "/images/emit-50.png", "tone": "Best seller", "category": "Emit series", "description": "Room-filling, energetic sound in a beautifully proportioned floorstander designed to make every playlist more engaging.", "specs": [["System", "3-way twin-woofer floorstander"], ["Frequency response", "31 Hz – 25 kHz (±3 dB)"], ["Sensitivity", "88.5 dB (2.83 V / 1 m)"], ["Nominal impedance", "6 Ω"], ["Recommended amplifier power", "40 – 180 W"], ["Crossover frequencies", "430 Hz / 3.1 kHz"], ["Dimensions (H × W × D)", "900 × 290 × 310 mm"], ["Weight", "22 kg each"], ["Cabinet finishes", "Black ash / White satin"]]},
    {"name": "Aether 7", "type": "Transparent floorstanding speaker", "price": "€18,900", "image": "/images/aether-glass-floorstander.png", "tone": "Material study", "category": "Aether series", "description": "A sculptural four-way system housed in acoustically inert smoked glass. The cabinet disappears visually while its exposed driver architecture makes every detail feel intentional.", "specs": [["System", "4-way open-frame glass floorstander"], ["Frequency response", "24 Hz – 32 kHz (±3 dB)"], ["Sensitivity", "91 dB (2.83 V / 1 m)"], ["Nominal impedance", "8 Ω (5.2 Ω minimum)"], ["Recommended amplifier power", "100 – 500 W"], ["Crossover frequencies", "180 Hz / 1.8 kHz / 7.5 kHz"], ["Maximum SPL", "116 dB at 1 m"], ["Dimensions (H × W × D)", "1180 × 290 × 390 mm"], ["Weight", "41 kg each"], ["Cabinet materials", "Smoked acoustic glass / Brushed aluminium"]]},
    {"name": "Terra One", "type": "Wireless sculptural speaker", "price": "€2,800", "image": "/images/terra-composite-wireless.png", "tone": "New material", "category": "Terra series", "description": "A compact active speaker cast from recycled mineral composite. Soft in silhouette, remarkably dense in sound, and designed to sit naturally in contemporary spaces.", "specs": [["System", "Coaxial active speaker with rear radiator"], ["Frequency response", "36 Hz – 21 kHz (±3 dB)"], ["Amplification", "280 W class-D with DSP"], ["Maximum SPL", "104 dB at 1 m"], ["Wireless", "Wi‑Fi 6 / AirPlay 2 / Bluetooth 5.3"], ["Inputs", "Optical / USB-C / line-in"], ["Room correction", "App-guided microphone calibration"], ["Dimensions (H × W × D)", "410 × 290 × 260 mm"], ["Weight", "12.5 kg"], ["Cabinet materials", "Recycled mineral composite / Graphite textile"]]},
    {"name": "Vector 12", "type": "Aluminium active monitor", "price": "€6,400", "image": "/images/vector-12.png", "tone": "Studio edition", "category": "Vector series", "description": "A precision active monitor machined from recycled aluminium. Its wave-guided tweeter and DSP alignment deliver controlled, close-field clarity without a conventional cabinet.", "specs": [["System", "3-way DSP active nearfield monitor"], ["Frequency response", "28 Hz – 26 kHz (±2 dB)"], ["Amplification", "500 W tri-amplified (ICEpower)"], ["Maximum SPL", "112 dB at 1 m"], ["Directivity", "90° × 50° waveguide"], ["Inputs", "Balanced XLR / AES3 / USB-C"], ["Calibration", "Network room EQ with 8 filters"], ["Dimensions (H × W × D)", "470 × 260 × 330 mm"], ["Weight", "18 kg each"], ["Cabinet materials", "Recycled aluminium / Space-black anodise"]]},
]
