import { useEffect, useMemo, useRef, useState, type MouseEvent } from 'react';
import { ArrowRight, ChevronDown, Heart, Menu, Search, ShoppingBag, X } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useWebMcp, type CartItem } from './hooks/useWebMcp';
import { apiUrl } from './lib/api';
import { getNeonJwt } from './lib/neonAuth';
import { createLocalBuild, readLocalBuilds, writeLocalBuilds, type LocalBuild } from './lib/localBuilds';
import ProceduralSpeaker from './components/ProceduralSpeaker';
import BuildSheetExporter from './components/BuildSheetExporter';
import { downloadDataUrl, generateBuildSheet } from './lib/buildSheet';
import SimulatorPage from './components/SimulatorPage';
import SimulationWorkspace from './components/SimulationWorkspace';
import ComparisonPage from './components/ComparisonPage';
import type { AcousticPlatformId, CabinetFinishId, CustomSpeakerBuild, CustomSpeakerCatalogResponse, CustomSpeakerConfiguration, PersonalisationKind, SoundProfile } from '@acoustom/types';

export type Product = { name: string; type: string; price: string; image: string; tone: string; category: string; description: string; specs: [string, string][] };

export default function App() {
  const navigate = useNavigate();
  const location = useLocation();
  const [products, setProducts] = useState<Product[]>([]);
  const [menuOpen, setMenuOpen] = useState(false); const [detail, setDetail] = useState<Product | null>(null); const [customOpen, setCustomOpen] = useState(false); const [liked, setLiked] = useState<string[]>([]); const [cart, setCart] = useState<CartItem[]>(() => { try { const saved = window.localStorage.getItem('acoustom-cart'); return saved ? JSON.parse(saved) as CartItem[] : []; } catch { return []; } });
  const cartRef = useRef(cart); const likedRef = useRef(liked);
  useEffect(() => { cartRef.current = cart; likedRef.current = liked; }, [cart, liked]);
  const pathProduct = products.find((product) => `/speakers/${product.name.toLowerCase().replace(/\s+/g, '-')}` === location.pathname);
  const activeDetail = detail ?? pathProduct ?? null;
  const simulatorOpen = location.pathname === '/simulator';
  const comparisonOpen = location.pathname === '/compare';
  const goHome = () => { setDetail(null); setCustomOpen(false); setMenuOpen(false); navigate('/'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const goTo = (id: string) => (event: MouseEvent<HTMLAnchorElement>) => { event.preventDefault(); setDetail(null); setCustomOpen(false); setMenuOpen(false); navigate(id === 'speakers' ? '/speakers' : `/#${id}`); window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50); };
  const goCustom = () => { setDetail(null); setCustomOpen(true); setMenuOpen(false); navigate('/custom-design'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const goSimulator = (product?: Product) => { setDetail(null); setCustomOpen(false); setMenuOpen(false); if (product) window.sessionStorage.setItem('acoustom-preview-speaker', product.name); navigate('/simulator'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const goCompare = () => { setDetail(null); setCustomOpen(false); setMenuOpen(false); navigate('/compare'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const openProduct = (product: Product) => { setDetail(product); setCustomOpen(false); navigate(`/speakers/${product.name.toLowerCase().replace(/\s+/g, '-')}`); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const backToSpeakers = () => { setDetail(null); setCustomOpen(false); navigate('/speakers'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const toggleLike = (name: string) => setLiked((items) => items.includes(name) ? items.filter((item) => item !== name) : [...items, name]);
  const addToCart = (productName: string, quantity: number) => { const existing = cartRef.current.find((item) => item.productName === productName); const next = existing ? cartRef.current.map((item) => item.productName === productName ? { ...item, quantity: item.quantity + quantity } : item) : [...cartRef.current, { productName, quantity }]; cartRef.current = next; setCart(next); return next; };
  const updateCartQuantity = (productName: string, quantity: number) => { const next = quantity === 0 ? cartRef.current.filter((item) => item.productName !== productName) : cartRef.current.map((item) => item.productName === productName ? { ...item, quantity } : item); cartRef.current = next; setCart(next); return next; };
  const removeFromCart = (productName: string) => updateCartQuantity(productName, 0);
  const toggleLikeAndReturn = (name: string) => { const currentlyLiked = !likedRef.current.includes(name); const next = currentlyLiked ? [...likedRef.current, name] : likedRef.current.filter((item) => item !== name); likedRef.current = next; setLiked(next); return currentlyLiked; };
  useEffect(() => { void fetch(apiUrl('/api/speakers/catalog')).then(async (response) => { if (!response.ok) throw new Error('Catalog unavailable'); return response.json() as Promise<{ products: Product[] }>; }).then(({ products: catalog }) => setProducts(catalog)).catch(() => undefined); }, []);
  useEffect(() => { window.localStorage.setItem('acoustom-cart', JSON.stringify(cart)); }, [cart]);
  useWebMcp({ products, getCart: () => cartRef.current, getLiked: () => likedRef.current, getAccessToken: getNeonJwt, addToCart, updateCartQuantity, removeFromCart, toggleLike: toggleLikeAndReturn });
  return <div className="site-shell">
    <div className="announcement">Free delivery on all orders over €500 <ArrowRight size={14} /></div>
    <header className="nav-wrap"><button className="menu-trigger" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}<span>Menu</span></button><button className="wordmark" onClick={goHome}>ACOUSTOM<span>®</span></button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><a href="#speakers" onClick={goTo('speakers')}>Speakers</a><button onClick={goCompare}>Compare</button><button onClick={() => goSimulator()}>Listening lab</button><a href="#journal" onClick={goTo('journal')}>Journal</a><button onClick={goCustom}>Custom design</button></nav><div className="nav-actions"><button aria-label="Search"><Search /></button><button aria-label={`Bag, ${cart.reduce((total, item) => total + item.quantity, 0)} items`}><ShoppingBag /><sup>{cart.reduce((total, item) => total + item.quantity, 0)}</sup></button></div></header>
    {activeDetail ? <ProductDetail product={activeDetail} onBack={backToSpeakers} /> : simulatorOpen ? <SimulatorPage products={products} onBack={goHome} /> : comparisonOpen ? <ComparisonPage products={products} onBack={backToSpeakers} onPreview={goSimulator} /> : customOpen || location.pathname === '/custom-design' ? <CustomDesign onBack={goHome} products={products} /> : <><main>
      <section className="hero"><div className="hero-copy"><p className="eyebrow">The new Contour i series</p><h1>Sound.<br /><em>Refined.</em></h1><p className="hero-intro">A century of acoustic craft, distilled into a listening experience that feels like nothing else.</p>{products[0] && <button className="button light" onClick={() => openProduct(products[0])}>Explore Contour 20i <ArrowRight size={16} /></button>}</div><div className="hero-image"><img src="https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1800&q=90" alt="Premium speaker in a warm listening room" /><div className="hero-caption">01 / 03<br /><span>Designed for the moments that matter.</span></div></div></section>
      <section className="intro-band" id="story"><p className="eyebrow">The Acoustom difference</p><h2>Made for <em>music.</em><br />Built for life.</h2><p>We believe great sound should disappear into the room and leave only the feeling behind. Every Acoustom loudspeaker is designed, tuned, and hand-finished in our studio.</p><a href="#journal" className="text-link">Discover our approach <ArrowRight size={15} /></a></section>
      <section className="catalog" id="speakers"><div className="section-head"><div><p className="eyebrow">Find your sound</p><h2>Explore the collection</h2></div><button className="filter">All speakers <ChevronDown size={16} /></button></div><div className="product-grid">{products.map((product) => <article className="product-card" key={product.name}><div className="product-image"><img src={product.image} alt={product.name} /><span>{product.tone}</span><button className="heart" onClick={() => toggleLike(product.name)} aria-label="Save product"><Heart fill={liked.includes(product.name) ? 'currentColor' : 'none'} /></button></div><button className="product-info" onClick={() => openProduct(product)}><div><h3>{product.name}</h3><p>{product.type}</p></div><strong>{product.price}</strong><ArrowRight size={17} /></button></article>)}</div></section>
      <section className="feature" id="journal"><img src="https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1600&q=85" alt="Listening room details" /><div><p className="eyebrow">The art of listening</p><h2>Hear more.<br /><em>Feel more.</em></h2><p>From the first note to the last, every detail matters. Learn how our engineers turn sound into something you can feel.</p><a href="#story" className="text-link">Read the story <ArrowRight size={15} /></a></div></section>
    </main><footer id="support"><div className="footer-brand">ACOUSTOM®<p>Beautiful sound, honestly made.</p></div><div><p className="footer-title">Explore</p><a href="#speakers" onClick={goTo('speakers')}>Speakers</a><a href="#story" onClick={goTo('story')}>Our story</a><a href="#journal" onClick={goTo('journal')}>Journal</a><button onClick={goCustom}>Custom design</button></div><div><p className="footer-title">Stay in the room</p><p>Join our newsletter for new releases,<br />listening notes, and studio stories.</p><div className="email"><span>Your email address</span><ArrowRight size={16} /></div></div></footer></>}
  </div>;
}
function ProductDetail({ product, onBack }: { product: Product; onBack: () => void }) { return <main className="detail-page"><button className="back-link" onClick={onBack}>← Back to collection</button><div className="detail-grid"><div className="detail-image"><img src={product.image} alt={product.name} /></div><div className="detail-copy"><p className="eyebrow">{product.tone} / {product.category}</p><h1>{product.name}</h1><p className="detail-type">{product.type}</p><p className="detail-price">{product.price} <span>per pair</span></p><p className="detail-description">{product.description}</p><button className="button dark">Add to bag <ArrowRight size={16} /></button><p className="detail-note">Complimentary delivery · 30-day listening trial</p></div></div><section className="detail-intro"><p className="eyebrow">The listening experience</p><h2>Everything you need.<br /><em>Nothing you don't.</em></h2><p>{product.name} is tuned for a natural, uncoloured presentation. Its controlled bass, open midrange, and effortless high frequencies let you hear the intent behind every recording.</p></section><section className="detail-panels"><div className="detail-panel"><p className="eyebrow">Engineering</p><h3>Built around the music</h3><p>Every cabinet, driver, and crossover decision is made to keep the signal clean and the timing coherent. This is the kind of detail you notice in the first bar—and appreciate for years.</p><a className="text-link" href="#specifications">See specifications <ArrowRight size={15} /></a></div><div className="detail-panel dark-panel"><p className="eyebrow">Room placement</p><h3>Give it room to breathe</h3><p>Start with the speakers slightly angled toward your listening position, then adjust by ear. We recommend a little space from the rear wall for the most open presentation.</p><button className="text-link">Open room guide <ArrowRight size={15} /></button></div></section><section className="specifications" id="specifications"><div className="spec-heading"><p className="eyebrow">Technical details</p><h2>Specifications</h2><p>Reference values for the {product.name}. These fields are structured to connect with the room simulator later.</p></div><div className="spec-table">{product.specs.map(([label, value]) => <div className="spec-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section><section className="detail-bottom"><p className="eyebrow">Find your fit</p><h2>Ready to hear<br /><em>the difference?</em></h2><button className="button dark" onClick={onBack}>Explore the collection <ArrowRight size={16} /></button></section></main>; }

function CustomDesign({ onBack, products }: { onBack: () => void; products: Product[] }) {
  const [localBuilds, setLocalBuilds] = useState<LocalBuild[]>(() => readLocalBuilds()?.builds ?? []);
  const [activeBuildId, setActiveBuildId] = useState<string | null>(() => readLocalBuilds()?.activeBuildId ?? null);
  const [localHydrated, setLocalHydrated] = useState(false);
  const [buildName, setBuildName] = useState('Untitled 01');
  const [finish, setFinish] = useState('Natural walnut'); const [shape, setShape] = useState('Standmount');
  const [activeStep, setActiveStep] = useState(0); const [platformId, setPlatformId] = useState<AcousticPlatformId>('two_way_compact'); const [soundProfile, setSoundProfile] = useState<SoundProfile>('balanced'); const [roomSize, setRoomSize] = useState<'small' | 'medium' | 'large'>('medium'); const [listeningDistanceM, setListeningDistanceM] = useState(2.5);
  const [enclosure, setEnclosure] = useState<'ported' | 'sealed'>('ported'); const [bassCharacter, setBassCharacter] = useState<'tight' | 'balanced' | 'extended'>('balanced'); const [tuning, setTuning] = useState(42); const [netVolumeLitres, setNetVolumeLitres] = useState(14); const [portInnerDiameterMm, setPortInnerDiameterMm] = useState(50); const [portLengthMm, setPortLengthMm] = useState(200); const [dampingDescription, setDampingDescription] = useState('150 g Acousto-Q, distributed away from the port');
  const [cabinetSize, setCabinetSize] = useState<'compact' | 'standard' | 'large'>('standard'); const [grille, setGrille] = useState<'none' | 'magnetic_fabric' | 'perforated_metal'>('magnetic_fabric'); const [base, setBase] = useState<'plinth' | 'slim_feet' | 'stand'>('stand'); const [edgeProfile, setEdgeProfile] = useState<'soft_radius' | 'sculpted_radius'>('soft_radius');
  const [personalisationKind, setPersonalisationKind] = useState<PersonalisationKind>('none'); const [engravingText, setEngravingText] = useState(''); const [artworkRightsConfirmed, setArtworkRightsConfirmed] = useState(false); const [build, setBuild] = useState<CustomSpeakerBuild | null>(null); const [submitError, setSubmitError] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const [isExporting, setIsExporting] = useState(false);
  const format = platformId === 'subwoofer_active' ? 'subwoofer' : shape === 'Standmount' ? 'standmount' : 'floorstanding';
  useEffect(() => {
    if (platformId === 'two_way_compact') {
      setShape('Standmount'); setEnclosure('ported'); setTuning(42); setNetVolumeLitres(14); setPortInnerDiameterMm(50); setPortLengthMm(200); setDampingDescription('150 g Acousto-Q, distributed away from the port');
    }
    if (platformId === 'three_way_reference') {
      setShape('Standmount'); setEnclosure('ported'); setTuning(30); setNetVolumeLitres(44); setPortInnerDiameterMm(67); setPortLengthMm(139.5); setDampingDescription('Light damping in marked enclosure areas, clear of drivers and port');
    }
  }, [platformId]);
  const [platformOptions, setPlatformOptions] = useState<Array<{ id: AcousticPlatformId; label: string }>>([{ id: 'two_way_compact', label: 'SEAS Mimir · 2-way' }, { id: 'two_way_extended', label: 'SEAS Aphel · 2-way' }, { id: 'three_way_reference', label: 'SEAS 403 Revisited · 3-way' }, { id: 'subwoofer_active', label: 'Dayton DCS165-4 active sub' }]);
  useEffect(() => {
    const loadCatalog = async () => {
      const response = await fetch(apiUrl('/api/custom-speakers/catalog'));
      if (!response.ok) return;
      const catalog = await response.json() as CustomSpeakerCatalogResponse;
      setPlatformOptions(catalog.platforms.map((platform) => ({ id: platform.id, label: `${platform.name} · ${platform.architecture.replace('_', '-')}` })));
    };
    void loadCatalog().catch(() => undefined);
  }, []);
  const finishId = ({ 'Natural walnut': 'walnut', 'Black ash': 'black_ash', 'Satin white': 'satin_white' } satisfies Record<string, CabinetFinishId>)[finish] ?? 'walnut';
  const configuration = useMemo<CustomSpeakerConfiguration>(() => ({
      version: 1, name: buildName,
      brief: { format, soundProfile, roomSize, listeningDistanceM },
      platformId, bass: { alignment: enclosure, bassCharacter, netVolumeLitres, ...(enclosure === 'ported' ? { tuningHz: tuning, portInnerDiameterMm, portLengthMm, dampingDescription } : {}) },
      cabinet: { size: cabinetSize, finish: finishId, finishFamily: finishId === 'walnut' || finishId === 'black_ash' ? 'veneer' : 'paint', grille, base: format === 'standmount' ? base : base === 'stand' ? 'slim_feet' : base, edgeProfile },
      personalisation: personalisationKind === 'engraving' ? { kind: 'engraving', engraving: { text: engravingText, font: 'modern_sans', placement: 'rear_badge' } } : personalisationKind === 'none' ? { kind: 'none' } : { kind: personalisationKind, artwork: { application: 'side_panel', treatment: 'matte_decal', rightsConfirmed: artworkRightsConfirmed, status: 'pending_upload' } },
  }), [artworkRightsConfirmed, base, bassCharacter, buildName, cabinetSize, dampingDescription, edgeProfile, enclosure, engravingText, finishId, format, grille, listeningDistanceM, netVolumeLitres, personalisationKind, platformId, portInnerDiameterMm, portLengthMm, roomSize, soundProfile, tuning]);
  const createBuild = async () => {
    setIsSubmitting(true); setSubmitError(null);
    try {
      const response = await fetch(apiUrl('/api/custom-speakers/'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(configuration) });
      if (!response.ok) {
        const body = await response.json().catch(() => null);
        const detail = body?.detail;
        throw new Error(typeof detail === 'string' ? detail : detail ? JSON.stringify(detail) : `Build validation failed (${response.status}).`);
      }
      const nextBuild = await response.json() as CustomSpeakerBuild;
      setBuild(nextBuild);
      window.sessionStorage.setItem('acoustom-custom-speaker-profile', JSON.stringify(nextBuild.derived.simulationProfile));
      setLocalBuilds((items) => items.map((item) => item.id === activeBuildId ? { ...item, simulationProfile: nextBuild.derived.simulationProfile, updatedAt: new Date().toISOString() } : item));
    } catch (error) { setSubmitError(error instanceof Error ? error.message : 'The build could not be submitted.'); }
    finally { setIsSubmitting(false); }
  };
  const downloadBuildSheet = async () => { if (!build) return; setIsExporting(true); try { const image = await generateBuildSheet({ configuration, derived: build.derived }); downloadDataUrl(image, `acoustom-${buildName.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'custom-build'}-build-sheet.png`); } catch (error) { setSubmitError(error instanceof Error ? error.message : 'Could not generate the build sheet.'); } finally { setIsExporting(false); } };
  const applyConfiguration = (config: CustomSpeakerConfiguration) => {
    setBuildName(config.name);
    setPlatformId(config.platformId); setShape(config.brief.format === 'floorstanding' ? 'Floorstanding' : 'Standmount'); setSoundProfile(config.brief.soundProfile); setRoomSize(config.brief.roomSize); setListeningDistanceM(config.brief.listeningDistanceM);
    setEnclosure(config.bass.alignment); setBassCharacter(config.bass.bassCharacter); setTuning(config.bass.tuningHz ?? 42); setNetVolumeLitres(config.bass.netVolumeLitres ?? 14); setPortInnerDiameterMm(config.bass.portInnerDiameterMm ?? 50); setPortLengthMm(config.bass.portLengthMm ?? 200); setDampingDescription(config.bass.dampingDescription ?? '');
    setCabinetSize(config.cabinet.size); setGrille(config.cabinet.grille); setBase(config.cabinet.base); setEdgeProfile(config.cabinet.edgeProfile); setFinish(({ walnut: 'Natural walnut', black_ash: 'Black ash', satin_white: 'Satin white' } as Record<string, string>)[config.cabinet.finish] ?? 'Natural walnut'); setPersonalisationKind(config.personalisation.kind); setEngravingText(config.personalisation.engraving?.text ?? ''); setArtworkRightsConfirmed(config.personalisation.artwork?.rightsConfirmed ?? false);
  };
  useEffect(() => {
    if (localHydrated) return;
    const stored = readLocalBuilds();
    if (stored) {
      const active = stored.builds.find((item) => item.id === stored.activeBuildId) ?? stored.builds[0];
      setLocalBuilds(stored.builds); setActiveBuildId(active.id); applyConfiguration(active.configuration);
      if (active.simulationProfile) window.sessionStorage.setItem('acoustom-custom-speaker-profile', JSON.stringify(active.simulationProfile));
    } else {
      const first = createLocalBuild(configuration);
      setLocalBuilds([first]); setActiveBuildId(first.id);
    }
    setLocalHydrated(true);
  // The initial configuration is deliberately used only to seed an empty library.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [localHydrated]);
  useEffect(() => {
    if (!localHydrated || !activeBuildId) return;
    const timer = window.setTimeout(() => setLocalBuilds((items) => items.map((item) => item.id === activeBuildId ? { ...item, name: configuration.name, configuration, updatedAt: new Date().toISOString() } : item)), 350);
    return () => window.clearTimeout(timer);
  }, [activeBuildId, configuration, localHydrated]);
  useEffect(() => { if (localHydrated && activeBuildId) writeLocalBuilds({ builds: localBuilds, activeBuildId }); }, [activeBuildId, localBuilds, localHydrated]);
  const selectLocalBuild = (id: string) => {
    const item = localBuilds.find((candidate) => candidate.id === id);
    if (!item) return;
    setActiveBuildId(id); applyConfiguration(item.configuration); setBuild(null); setSubmitError(null);
    if (item.simulationProfile) window.sessionStorage.setItem('acoustom-custom-speaker-profile', JSON.stringify(item.simulationProfile));
    else window.sessionStorage.removeItem('acoustom-custom-speaker-profile');
  };
  const newLocalBuild = () => { const item = createLocalBuild({ ...configuration, name: `Untitled ${localBuilds.length + 1}` }); setLocalBuilds((items) => [...items, item]); setActiveBuildId(item.id); setBuildName(item.name); setBuild(null); };
  const duplicateLocalBuild = () => { const current = localBuilds.find((item) => item.id === activeBuildId); if (!current) return; const item = createLocalBuild(current.configuration, `${current.name} copy`); item.simulationProfile = current.simulationProfile; setLocalBuilds((items) => [...items, item]); setActiveBuildId(item.id); setBuildName(item.name); };
  const deleteLocalBuild = () => { if (localBuilds.length <= 1 || !activeBuildId) return; const remaining = localBuilds.filter((item) => item.id !== activeBuildId); setLocalBuilds(remaining); selectLocalBuild(remaining[0].id); };
  const steps = ['Brief', 'Platform', 'Bass', 'Cabinet', 'Finish', 'Personalisation', 'Review'];
  return <main className="editor-page"><BuildSheetExporter />
    <div className="editor-top"><button className="back-link" onClick={onBack}>← Back to collection</button><span className="editor-title">CUSTOM SPEAKER / <input aria-label="Build name" value={buildName} onChange={(event) => setBuildName(event.target.value)} /></span><div className="build-library"><select aria-label="Choose saved local build" value={activeBuildId ?? ''} onChange={(event) => selectLocalBuild(event.target.value)}>{localBuilds.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={newLocalBuild}>New</button><button onClick={duplicateLocalBuild}>Duplicate</button><button onClick={deleteLocalBuild} disabled={localBuilds.length <= 1}>Delete</button></div></div>
    <div className="step-tabs">{steps.map((step, i) => <button key={step} className={activeStep === i ? 'active' : activeStep > i ? 'done' : ''} onClick={() => setActiveStep(i)}><b>{String(i + 1).padStart(2, '0')}</b>{step}</button>)}</div>
    <section className="editor-workspace">
      <div className="editor-stage"><ProceduralSpeaker config={configuration} /><div className="stage-meta"><span>LIVE PREVIEW / {format.toUpperCase()}</span><span>DRAG TO ROTATE · SCROLL TO ZOOM</span></div><div className="stage-grid" /></div>
      <aside className="editor-panel"><div className="panel-heading"><div><p className="eyebrow">Step {String(activeStep + 1).padStart(2, '0')} of 07</p><h1>{steps[activeStep]}</h1></div><span className="status-dot" /></div>
        {activeStep === 0 && <><p className="panel-copy">Define the listening context used to select a suitable curated build.</p><label className="control-label">Speaker format</label>{platformId === 'subwoofer_active' ? <div className="placeholder-control"><span>FORMAT</span><strong>Subwoofer</strong></div> : <div className="segmented">{['Standmount', 'Floorstanding'].map((item) => <button key={item} className={shape === item ? 'selected' : ''} onClick={() => { setShape(item); if (item === 'Floorstanding' && base === 'stand') setBase('slim_feet'); }}>{item}</button>)}</div>}<div className="panel-section"><label className="control-label">Sound profile</label><div className="segmented">{(['balanced', 'reference', 'warm', 'immersive'] as SoundProfile[]).map((item) => <button key={item} className={soundProfile === item ? 'selected' : ''} onClick={() => setSoundProfile(item)}>{item}</button>)}</div></div><div className="panel-section"><label className="control-label">Room size</label><div className="segmented">{(['small', 'medium', 'large'] as const).map((item) => <button key={item} className={roomSize === item ? 'selected' : ''} onClick={() => setRoomSize(item)}>{item}</button>)}</div></div><label className="control-label range-label">Listening distance <strong>{listeningDistanceM.toFixed(1)} m</strong></label><input type="range" min="1.2" max="6" step=".1" value={listeningDistanceM} onChange={(e) => setListeningDistanceM(Number(e.target.value))} /></>}
        {activeStep === 1 && <><p className="panel-copy">The platform is the controlled engineering choice. Drivers are derived by the API, not selected independently.</p><label className="control-label">Acoustic platform</label><div className="editor-cards">{platformOptions.map((item) => <button key={item.id} className={platformId === item.id ? 'selected' : ''} onClick={() => { setPlatformId(item.id); if (item.id === 'two_way_compact') { setShape('Standmount'); setEnclosure('ported'); setTuning(42); } if (item.id === 'two_way_extended') { setShape('Floorstanding'); setEnclosure('ported'); setTuning(36); setBase('slim_feet'); } if (item.id === 'subwoofer_active') { setShape('Floorstanding'); setBase('slim_feet'); } }}><span className="mini-speaker">{item.id === 'three_way_reference' ? '●\n●\n●' : item.id === 'subwoofer_active' ? '◉' : '●\n●'}</span>{item.label}{platformId === item.id && <b>✓</b>}</button>)}</div></>}
        {activeStep === 2 && <><p className="panel-copy">Every acoustic variable is submitted to the build. A changed enclosure needs a newly measured system profile.</p><label className="control-label">Enclosure type</label><div className="segmented"><button className={enclosure === 'ported' ? 'selected' : ''} onClick={() => setEnclosure('ported')}>Bass reflex</button><button className={enclosure === 'sealed' ? 'selected' : ''} onClick={() => setEnclosure('sealed')}>Sealed</button></div><div className="panel-section"><label className="control-label">Bass character</label><div className="segmented">{(['tight', 'balanced', 'extended'] as const).map((item) => <button key={item} className={bassCharacter === item ? 'selected' : ''} onClick={() => setBassCharacter(item)}>{item}</button>)}</div></div>{enclosure === 'ported' && <><label className="control-label range-label">Port tuning <strong>{tuning} Hz</strong></label><input type="range" min="24" max="65" value={tuning} onChange={(e) => setTuning(Number(e.target.value))} /><label className="control-label">Net internal volume (L)</label><input type="number" min="1" max="250" value={netVolumeLitres} onChange={(e) => setNetVolumeLitres(Number(e.target.value))} /><label className="control-label">Port inner diameter (mm)</label><input type="number" min="1" max="250" value={portInnerDiameterMm} onChange={(e) => setPortInnerDiameterMm(Number(e.target.value))} /><label className="control-label">Port length (mm)</label><input type="number" min="1" max="1000" value={portLengthMm} onChange={(e) => setPortLengthMm(Number(e.target.value))} /><label className="control-label">Damping treatment</label><input value={dampingDescription} onChange={(e) => setDampingDescription(e.target.value)} /></>}</>}
        {activeStep === 3 && <><p className="panel-copy">These cabinet choices map one-for-one to the submitted configuration.</p><label className="control-label">Cabinet size</label><div className="segmented">{(['compact', 'standard', 'large'] as const).map((item) => <button key={item} className={cabinetSize === item ? 'selected' : ''} onClick={() => setCabinetSize(item)}>{item}</button>)}</div><div className="panel-section"><label className="control-label">Grille</label><div className="segmented">{(['none', 'magnetic_fabric', 'perforated_metal'] as const).map((item) => <button key={item} className={grille === item ? 'selected' : ''} onClick={() => setGrille(item)}>{item.replace('_', ' ')}</button>)}</div></div><div className="panel-section"><label className="control-label">Base</label><div className="segmented">{(['plinth', 'slim_feet', 'stand'] as const).map((item) => <button key={item} disabled={item === 'stand' && format !== 'standmount'} className={base === item ? 'selected' : ''} onClick={() => setBase(item)}>{item.replace('_', ' ')}</button>)}</div></div><div className="panel-section"><label className="control-label">Edge profile</label><div className="segmented">{(['soft_radius', 'sculpted_radius'] as const).map((item) => <button key={item} className={edgeProfile === item ? 'selected' : ''} onClick={() => setEdgeProfile(item)}>{item.replace('_', ' ')}</button>)}</div></div></>}
        {activeStep === 4 && <><p className="panel-copy">Finish is a physical product choice and includes its compatible finish family.</p><label className="control-label">Finish</label><div className="finish-list">{['Natural walnut', 'Black ash', 'Satin white'].map((item) => <button key={item} className={finish === item ? 'selected' : ''} onClick={() => setFinish(item)}><span className={`swatch ${item.replace(' ', '-')}`} />{item}<b>{finish === item ? '✓' : ''}</b></button>)}</div></>}
        {activeStep === 5 && <><p className="panel-copy">Personalisation is submitted for manufacturing review.</p><label className="control-label">Treatment</label><div className="segmented">{(['none', 'engraving', 'pattern', 'printed_panel', 'decal', 'custom_artwork'] as PersonalisationKind[]).map((item) => <button key={item} className={personalisationKind === item ? 'selected' : ''} onClick={() => setPersonalisationKind(item)}>{item.replace('_', ' ')}</button>)}</div>{personalisationKind === 'engraving' && <div className="panel-section"><label className="control-label">Engraving text</label><input value={engravingText} maxLength={32} onChange={(e) => setEngravingText(e.target.value)} /></div>}{!['none', 'engraving'].includes(personalisationKind) && <label className="panel-copy"><input type="checkbox" checked={artworkRightsConfirmed} onChange={(e) => setArtworkRightsConfirmed(e.target.checked)} /> I confirm I have rights to the artwork.</label>}</>}
        {activeStep === 6 && <><p className="panel-copy">Review the build specification. Measured acoustic performance is released only after driver, enclosure and crossover validation.</p><div className="simulation-card"><div className="response-lines"><i /><i /><i /><i /><i /></div><span>{build ? build.derived.simulationProfile.status.replace('_', ' ') : 'Ready to validate'}</span><strong>{build ? `${build.derived.acousticDesign.alignment}${build.derived.acousticDesign.portTuningHz ? ` · ${build.derived.acousticDesign.portTuningHz} Hz tuning` : ''}` : enclosure === 'ported' ? `${tuning} Hz port tuning` : 'Sealed alignment'}</strong></div>{build && <div className="spec-table"><div className="spec-row"><span>Reference system</span><strong>{build.derived.simulationProfile.referenceName}</strong></div><div className="spec-row"><span>Bandwidth</span><strong>{build.derived.simulationProfile.frequencyRangeHz.join('–')} Hz</strong></div><div className="spec-row"><span>Cabinet</span><strong>{build.derived.physicalBuild.cabinetSize} · {build.derived.physicalBuild.finish.replaceAll('_', ' ')}</strong></div><div className="spec-row"><span>Room brief</span><strong>{build.derived.roomRecommendation.roomSize} · {build.derived.roomRecommendation.listeningDistanceM} m</strong></div></div>}{build?.derived.warnings.map((warning) => <p className="panel-copy" key={warning}>{warning}</p>)}{submitError && <p className="panel-copy">{submitError}</p>}<button className="simulate-button" disabled={isSubmitting} onClick={createBuild}>{isSubmitting ? 'Validating build…' : build ? 'Build validated ✓' : 'Validate custom build'} <ArrowRight size={15} /></button>{build && <button className="save-button" disabled={isExporting} onClick={downloadBuildSheet}>{isExporting ? 'Preparing build sheet…' : 'Download build sheet'}</button>}</>}
        {build && <SimulationWorkspace products={products} embedded />}
        {build && <div className="spec-table"><div className="spec-row"><span>Net enclosure volume</span><strong>{build.derived.acousticDesign.netVolumeLitres ?? '—'} L</strong></div><div className="spec-row"><span>Port geometry</span><strong>{build.derived.acousticDesign.portInnerDiameterMm && build.derived.acousticDesign.portLengthMm ? `${build.derived.acousticDesign.portInnerDiameterMm} mm × ${build.derived.acousticDesign.portLengthMm} mm` : 'Sealed / not specified'}</strong></div><div className="spec-row"><span>Damping</span><strong>{build.derived.acousticDesign.dampingDescription ?? '—'}</strong></div><div className="spec-row"><span>Model evidence</span><strong>{build.derived.simulationProfile.modelType.replaceAll('_', ' ')}</strong></div></div>}
        {build && <div className="panel-section"><label className="control-label">Verified source assets</label>{build.derived.simulationProfile.sourceAssets.map((asset) => <a className="text-link" key={`${asset.kind}-${asset.sourceUrl}`} href={asset.sourceUrl} target="_blank" rel="noreferrer">{asset.kind.replaceAll('_', ' ')} · {asset.description}</a>)}</div>}
        {build?.derived.simulationProfile.measurementRequiredFor?.length ? <div className="panel-section"><label className="control-label">Measurement status</label><p className="panel-copy">Simulation is available; validate these items before production: {build.derived.simulationProfile.measurementRequiredFor?.join(' · ')}</p></div> : null}

        <div className="panel-footer"><button onClick={() => setActiveStep(Math.max(0, activeStep - 1))} disabled={activeStep === 0}>← Previous</button><button className="next-button" onClick={() => setActiveStep(Math.min(6, activeStep + 1))}>{activeStep === 6 ? 'Finish design' : 'Next step'} <ArrowRight size={15} /></button></div>
      </aside>
    </section>
  </main>;
}
