import { useEffect, useRef, useState, type MouseEvent } from 'react';
import { ArrowRight, ChevronDown, Heart, Menu, Search, ShoppingBag, X } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useWebMcp, type CartItem, type WebMcpStatus } from './hooks/useWebMcp';

type Product = { name: string; type: string; price: string; image: string; tone: string; category: string; description: string; specs: [string, string][] };
const products: Product[] = [
  { name: 'Contour 20i', type: 'Standmount speaker', price: '€5,000', tone: 'New', category: 'Contour series', description: 'A meticulously balanced loudspeaker for people who want to get closer to the music. Open, honest, and effortless from the very first listen.', specs: [['Frequency response', '39 Hz – 23 kHz ±3 dB'], ['Sensitivity', '86 dB (2.83 V / 1 m)'], ['Impedance', '4 Ω'], ['Recommended power', '30 – 180 W'], ['Dimensions (H × W × D)', '440 × 215 × 360 mm'], ['Weight', '15 kg'], ['Finishes', 'Natural walnut / Black ash']], image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1100&q=85' },
  { name: 'Confidence 20', type: 'High-end standmount', price: '€32,000', tone: 'Signature', category: 'Confidence series', description: 'A reference standmount speaker with a wide, precise soundstage and the composure to reveal every nuance in your favourite recording.', specs: [['Frequency response', '42 Hz – 22 kHz ±3 dB'], ['Sensitivity', '87 dB (2.83 V / 1 m)'], ['Impedance', '4 Ω'], ['Recommended power', '50 – 250 W'], ['Dimensions (H × W × D)', '520 × 250 × 430 mm'], ['Weight', '27 kg'], ['Finishes', 'Black high gloss / Walnut']], image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=1100&q=85' },
  { name: 'Emit 50', type: 'Floorstanding speaker', price: '€2,200', tone: 'Best seller', category: 'Emit series', description: 'Room-filling, energetic sound in a beautifully proportioned floorstander designed to make every playlist more engaging.', specs: [['Frequency response', '33 Hz – 23 kHz ±3 dB'], ['Sensitivity', '87 dB (2.83 V / 1 m)'], ['Impedance', '4 Ω'], ['Recommended power', '40 – 200 W'], ['Dimensions (H × W × D)', '900 × 290 × 310 mm'], ['Weight', '22 kg'], ['Finishes', 'Black ash / White satin']], image: 'https://images.unsplash.com/photo-1598387993281-cecf8b71a8f8?auto=format&fit=crop&w=1100&q=85' },
];

export default function App() {
  const navigate = useNavigate();
  const location = useLocation();
  const [menuOpen, setMenuOpen] = useState(false); const [detail, setDetail] = useState<Product | null>(null); const [customOpen, setCustomOpen] = useState(false); const [liked, setLiked] = useState<string[]>([]); const [cart, setCart] = useState<CartItem[]>(() => { try { const saved = window.localStorage.getItem('acoustom-cart'); return saved ? JSON.parse(saved) as CartItem[] : []; } catch { return []; } });
  const cartRef = useRef(cart); const likedRef = useRef(liked); cartRef.current = cart; likedRef.current = liked;
  const pathProduct = products.find((product) => `/speakers/${product.name.toLowerCase().replace(/\s+/g, '-')}` === location.pathname);
  const activeDetail = detail ?? pathProduct ?? null;
  const goHome = () => { setDetail(null); setCustomOpen(false); setMenuOpen(false); navigate('/'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const goTo = (id: string) => (event: MouseEvent<HTMLAnchorElement>) => { event.preventDefault(); setDetail(null); setCustomOpen(false); setMenuOpen(false); navigate(id === 'speakers' ? '/speakers' : `/#${id}`); window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50); };
  const goCustom = () => { setDetail(null); setCustomOpen(true); setMenuOpen(false); navigate('/custom-design'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const openProduct = (product: Product) => { setDetail(product); setCustomOpen(false); navigate(`/speakers/${product.name.toLowerCase().replace(/\s+/g, '-')}`); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const backToSpeakers = () => { setDetail(null); setCustomOpen(false); navigate('/speakers'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const toggleLike = (name: string) => setLiked((items) => items.includes(name) ? items.filter((item) => item !== name) : [...items, name]);
  const addToCart = (productName: string, quantity: number) => { const existing = cartRef.current.find((item) => item.productName === productName); const next = existing ? cartRef.current.map((item) => item.productName === productName ? { ...item, quantity: item.quantity + quantity } : item) : [...cartRef.current, { productName, quantity }]; cartRef.current = next; setCart(next); return next; };
  const updateCartQuantity = (productName: string, quantity: number) => { const next = quantity === 0 ? cartRef.current.filter((item) => item.productName !== productName) : cartRef.current.map((item) => item.productName === productName ? { ...item, quantity } : item); cartRef.current = next; setCart(next); return next; };
  const removeFromCart = (productName: string) => updateCartQuantity(productName, 0);
  const toggleLikeAndReturn = (name: string) => { const currentlyLiked = !likedRef.current.includes(name); const next = currentlyLiked ? [...likedRef.current, name] : likedRef.current.filter((item) => item !== name); likedRef.current = next; setLiked(next); return currentlyLiked; };
  useEffect(() => { window.localStorage.setItem('acoustom-cart', JSON.stringify(cart)); }, [cart]);
  const webmcpStatus = useWebMcp({ products, getCart: () => cartRef.current, getLiked: () => likedRef.current, addToCart, updateCartQuantity, removeFromCart, toggleLike: toggleLikeAndReturn });
  return <div className="site-shell">
    <WebMcpStatusPanel status={webmcpStatus} />
    <div className="announcement">Free delivery on all orders over €500 <ArrowRight size={14} /></div>
    <header className="nav-wrap"><button className="menu-trigger" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}<span>Menu</span></button><button className="wordmark" onClick={goHome}>ACOUSTOM<span>®</span></button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><a href="#speakers" onClick={goTo('speakers')}>Speakers</a><a href="#story" onClick={goTo('story')}>Our story</a><a href="#journal" onClick={goTo('journal')}>Journal</a><button onClick={goCustom}>Custom design</button><a href="#support" onClick={goTo('support')}>Support</a></nav><div className="nav-actions"><button aria-label="Search"><Search /></button><button aria-label={`Bag, ${cart.reduce((total, item) => total + item.quantity, 0)} items`}><ShoppingBag /><sup>{cart.reduce((total, item) => total + item.quantity, 0)}</sup></button></div></header>
    {activeDetail ? <ProductDetail product={activeDetail} onBack={backToSpeakers} /> : customOpen || location.pathname === '/custom-design' ? <CustomDesign onBack={goHome} /> : <><main>
      <section className="hero"><div className="hero-copy"><p className="eyebrow">The new Contour i series</p><h1>Sound.<br /><em>Refined.</em></h1><p className="hero-intro">A century of acoustic craft, distilled into a listening experience that feels like nothing else.</p><button className="button light" onClick={() => openProduct(products[0])}>Explore Contour 20i <ArrowRight size={16} /></button></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1800&q=90" alt="Premium speaker in a warm listening room" /><div className="hero-caption">01 / 03<br /><span>Designed for the moments that matter.</span></div></div></section>
      <section className="intro-band" id="story"><p className="eyebrow">The Acoustom difference</p><h2>Made for <em>music.</em><br />Built for life.</h2><p>We believe great sound should disappear into the room and leave only the feeling behind. Every Acoustom loudspeaker is designed, tuned, and hand-finished in our studio.</p><a href="#journal" className="text-link">Discover our approach <ArrowRight size={15} /></a></section>
      <section className="catalog" id="speakers"><div className="section-head"><div><p className="eyebrow">Find your sound</p><h2>Explore the collection</h2></div><button className="filter">All speakers <ChevronDown size={16} /></button></div><div className="product-grid">{products.map((product) => <article className="product-card" key={product.name}><div className="product-image"><img src={product.image} alt={product.name} /><span>{product.tone}</span><button className="heart" onClick={() => toggleLike(product.name)} aria-label="Save product"><Heart fill={liked.includes(product.name) ? 'currentColor' : 'none'} /></button></div><button className="product-info" onClick={() => openProduct(product)}><div><h3>{product.name}</h3><p>{product.type}</p></div><strong>{product.price}</strong><ArrowRight size={17} /></button></article>)}</div></section>
      <section className="feature" id="journal"><img src="https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1600&q=85" alt="Listening room details" /><div><p className="eyebrow">The art of listening</p><h2>Hear more.<br /><em>Feel more.</em></h2><p>From the first note to the last, every detail matters. Learn how our engineers turn sound into something you can feel.</p><a href="#story" className="text-link">Read the story <ArrowRight size={15} /></a></div></section>
    </main><footer id="support"><div className="footer-brand">ACOUSTOM®<p>Beautiful sound, honestly made.</p></div><div><p className="footer-title">Explore</p><a href="#speakers" onClick={goTo('speakers')}>Speakers</a><a href="#story" onClick={goTo('story')}>Our story</a><a href="#journal" onClick={goTo('journal')}>Journal</a><button onClick={goCustom}>Custom design</button></div><div><p className="footer-title">Stay in the room</p><p>Join our newsletter for new releases,<br />listening notes, and studio stories.</p><div className="email"><span>Your email address</span><ArrowRight size={16} /></div></div></footer></>}
  </div>;
}
function ProductDetail({ product, onBack }: { product: Product; onBack: () => void }) { return <main className="detail-page"><button className="back-link" onClick={onBack}>← Back to collection</button><div className="detail-grid"><div className="detail-image"><img src={product.image} alt={product.name} /></div><div className="detail-copy"><p className="eyebrow">{product.tone} / {product.category}</p><h1>{product.name}</h1><p className="detail-type">{product.type}</p><p className="detail-price">{product.price} <span>per pair</span></p><p className="detail-description">{product.description}</p><button className="button dark">Add to bag <ArrowRight size={16} /></button><p className="detail-note">Complimentary delivery · 30-day listening trial</p></div></div><section className="detail-intro"><p className="eyebrow">The listening experience</p><h2>Everything you need.<br /><em>Nothing you don't.</em></h2><p>{product.name} is tuned for a natural, uncoloured presentation. Its controlled bass, open midrange, and effortless high frequencies let you hear the intent behind every recording.</p></section><section className="detail-panels"><div className="detail-panel"><p className="eyebrow">Engineering</p><h3>Built around the music</h3><p>Every cabinet, driver, and crossover decision is made to keep the signal clean and the timing coherent. This is the kind of detail you notice in the first bar—and appreciate for years.</p><a className="text-link" href="#specifications">See specifications <ArrowRight size={15} /></a></div><div className="detail-panel dark-panel"><p className="eyebrow">Room placement</p><h3>Give it room to breathe</h3><p>Start with the speakers slightly angled toward your listening position, then adjust by ear. We recommend a little space from the rear wall for the most open presentation.</p><button className="text-link">Open room guide <ArrowRight size={15} /></button></div></section><section className="specifications" id="specifications"><div className="spec-heading"><p className="eyebrow">Technical details</p><h2>Specifications</h2><p>Reference values for the {product.name}. These fields are structured to connect with the room simulator later.</p></div><div className="spec-table">{product.specs.map(([label, value]) => <div className="spec-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section><section className="detail-bottom"><p className="eyebrow">Find your fit</p><h2>Ready to hear<br /><em>the difference?</em></h2><button className="button dark" onClick={onBack}>Explore the collection <ArrowRight size={16} /></button></section></main>; }

function CustomDesign({ onBack }: { onBack: () => void }) { const [finish, setFinish] = useState('Natural walnut'); const [shape, setShape] = useState('Standmount'); return <main className="custom-page"><button className="back-link" onClick={onBack}>← Back to collection</button><section className="custom-hero"><div><p className="eyebrow">Acoustom atelier</p><h1>Your sound.<br /><em>Your object.</em></h1><p>Design a speaker that belongs in your room. Choose a form, a finish, and a sound profile—then preview the direction before we build it.</p></div><div className="custom-preview"><div className={`speaker-preview ${shape === 'Floorstanding' ? 'tall' : ''}`}><span /></div><p>Concept preview / 01</p></div></section><section className="custom-builder"><div className="builder-copy"><p className="eyebrow">01 — Make it yours</p><h2>Start with<br /><em>the details.</em></h2><p>This is a visual starting point for your custom build. The final configuration will be connected to your room profile and acoustic preferences in the simulator.</p></div><div className="builder-controls"><div><label>Cabinet form</label><div className="choice-row">{['Standmount', 'Floorstanding'].map((item) => <button className={shape === item ? 'selected' : ''} onClick={() => setShape(item)} key={item}>{item}</button>)}</div></div><div><label>Finish</label><div className="choice-row">{['Natural walnut', 'Black ash', 'Satin white'].map((item) => <button className={finish === item ? 'selected' : ''} onClick={() => setFinish(item)} key={item}>{item}</button>)}</div></div><div className="build-summary"><span>{shape} / {finish}</span><strong>From €4,800</strong></div><button className="button dark">Continue to sound profile <ArrowRight size={16} /></button></div></section><section className="custom-foot"><p className="eyebrow">Made to order</p><h2>One room.<br /><em>One pair.</em></h2><p>When you are ready, our design team will help translate your choices into a speaker tuned for the way you listen.</p><button className="text-link">Talk to an advisor <ArrowRight size={15} /></button></section></main>; }
